### ISSUE TITLE
Problems adding graph to database

### ISSUE THREAD

**Issue by mseesquared** [percyliang/sempre#10]
When trying to add tutorial.ttl to my virtuoso server, I got the following error:

RUNNING: echo "DB.DBA.TTLP_MT (file_to_string_output ('/Users/yushiwang/Documents/stanford13-14/pliang/virtuoso-3001-0.ttl'), '', 'http://rdf.freebase.com', 128);" | scripts/../virtuoso-opensource/install/bin/isql localhost:13001 2>&1 | tee virtuoso-3001-0.out
Connected to OpenLink Virtuoso
Driver: 06.01.3127 OpenLink Virtuoso ODBC Driver
OpenLink Interactive SQL (Virtuoso), version 0.9849b.
Type HELP; for help and EXIT; to exit.
SQL> 
*** Error 08S01: [Virtuoso Driver]CL065: Lost connection to server
at line 1 of Top-Level:
DB.DBA.TTLP_MT (file_to_string_output ('/Users/yushiwang/Documents/stanford13-14/pliang/virtuoso-3001-0.ttl'), '', 'http://rdf.freebase.com', 128)
RUNNING: cat virtuoso-3001-0.out >> virtuoso-3001.log
[Fri Jan 03 09:50:07 -0800 2014] FAILED

After getting this error, my server also gets stopped. Anybody know what the issue is here?

**Comment by percyliang** [comment]
I think at this point, the best options are either to use another triple store (SEMPRE doesn't really depend on Virtuoso - it just needs a SPARQL endpoint) or try to ask the Virtuoso people (since it seems to be a problem specific to Virtuoso).
