### ISSUE TITLE
true/pred derivation

### ISSUE THREAD

**Issue by hjw9673** [percyliang/sempre#103]
When I take a look at the log produced by ./run @mode=tables @data=u-1 @feat=all @train=0, 

I see two parts of derivations, true@ and pred@.

How is each of them produced and what does each of them mean?

+) How is each derivation scored? (Based on what?)

Thank you!

**Comment by ppasupat** [comment]
Each Derivation is scored based on the log-linear model (essentially dot product between `builder.params`, which is the same as `learner.params`, and `derivation.localFeatureVector`).
The derivations are then sorted based on their model scores; the derivation at ranked 0 has the highest score.

The `True@xxx` / `Pred@xxx` part is generated by the `parser.addToEvaluation` method.
`Pred@xxx` shows the derivation at rank `xxx`, while `True@xxx` says that the derivation at rank `xxx` gives the correct denotation. If none of the produced derivations give the correct denotation, the `True@xxx` tag will be absent. The parser gets one accuracy point if `True@0` is present.
