### ISSUE TITLE
issue: freebase/scripts/virtuoso start tutorial.vdb 3001

### ISSUE THREAD

**Issue by RobinCai1993** [percyliang/sempre#116]
I am using mac 10.11 and I can not get through this step. The issue is:
```
cat: /proc/meminfo: No such file or directory
freebase/scripts/virtuoso:18:in `Integer': invalid value for Integer(): "" (ArgumentError)
	from freebase/scripts/virtuoso:18:in `parseInt'
	from freebase/scripts/virtuoso:43:in `start'
	from freebase/scripts/virtuoso:221:in `<main>'
```
If I use in to replace `cat /proc/meminfo | grep MemFree | awk '{print $2}'`, the issue will be:
````
==== Starting Virtuoso server for tutorial.vdb on port 3001...
RUNNING: virtuoso-opensource/install/bin/virtuoso-t +configfile tutorial.vdb/virtuoso.ini +wait
FAILED: virtuoso-opensource/install/bin/virtuoso-t +configfile tutorial.vdb/virtuoso.ini +wait
````
Can this step be done on mac os?

**Comment by ppasupat** [comment]
Could you try running the command 
```
virtuoso-opensource/install/bin/virtuoso-t +configfile tutorial.vdb/virtuoso.ini +wait
```
directly and see what error is being thrown?

**Comment by ppasupat** [comment]
Alternatively, try running
```
freebase/scripts/virtuoso start tutorial.vdb 3001 2000000000
```
where 2000000000 is the number of _bytes_ you want to allocate memory for virtuoso. You might want to replace 2000000000 with ~70% of the available RAM.

**Comment by RobinCai1993** [comment]
If I try:
 `virtuoso-opensource/install/bin/virtuoso-t +configfile tutorial.vdb/virtuoso.ini +wait`
the output is:
`-bash: virtuoso-opensource/install/bin/virtuoso-t: No such file or directory
`
And if I try:
freebase/scripts/virtuoso start tutorial.vdb 3001 2000000000
the output is:
`2000000000000 KB free, using 175000000000 buffers, 87500000000 dirty buffers
==== Starting Virtuoso server for tutorial.vdb on port 3001...
RUNNING: virtuoso-opensource/install/bin/virtuoso-t +configfile tutorial.vdb/virtuoso.ini +wait
FAILED: virtuoso-opensource/install/bin/virtuoso-t +configfile tutorial.vdb/virtuoso.ini +wait`

**Comment by RobinCai1993** [comment]
I used brew to install virtuoso. 
And I also tried to install it by ./pull-dependencies virtuoso with the commands annotated in the pull-dependencies file. But it can not go through 'make install'. The errors are:
```
Making install in .
make[1]: *** No rule to make target `INSTALL', needed by `all-am'.  Stop.
make: *** [install-recursive] Error 1
```

**Comment by ppasupat** [comment]
> If I try:
> `virtuoso-opensource/install/bin/virtuoso-t +configfile tutorial.vdb/virtuoso.ini +wait`
> the output is:
> ```
> -bash: virtuoso-opensource/install/bin/virtuoso-t: No such file or directory
> ```

It seems that the command failed because `virtuoso-t` is not found. Could you try finding where the file is in the virtuoso directory (e.g., by running `find virtuoso -name virtuoso-t`)?

If that does not work, try a clean install:
* remove the `virtuoso-opensource` directory
* do 
```
./pull-dependencies virtuoso
cd virtuoso-opensource
./autogen.sh
./configure --prefix=$PWD/install
touch INSTALL
make
make install
```

**Comment by RobinCai1993** [comment]
Thank you! I've solved it by changing the paths in virtuoso.init.

**Comment by chentc** [comment]
@ppasupat I followed your instructions to configure virtuoso, but it failed. Below is the error message in config.log

conftest.c:11:10: fatal error: 'ac_nonexistent.h' file not found
#include <ac_nonexistent.h>

Any ideas why? Thanks!

**Comment by ppasupat** [comment]
Are you using a Mac? This error seems to indicate a missing library. Could you try using brew to install virtuoso:
```
brew install virtuoso
```

**Comment by ppasupat** [comment]
Otherwise, try looking for your OS in this document and type the corresponding command before `./configure`:
https://virtuoso.openlinksw.com/dataspace/doc/dav/wiki/Main/VOSMake

**Comment by chentc** [comment]
Yes I am using a Mac. I tried install virtuoso using homebrew. But do I need to set up anything inside of the sempre folder? 

When I run  

`freebase/scripts/virtuoso` start tutorial.vdb 3001'

I got 
freebase/scripts/../../virtuoso-opensource does not exist

**Comment by chentc** [comment]
I changed the path of virtuoso in the virtuoso script, from
`$virtuosoPath = File.dirname($0)+"/../../virtuoso-opensource"`
to my local path 
`$virtuosoPath = "/usr/local/Cellar/virtuoso"`,

and it worked. Thanks!

**Comment by appymittal** [comment]
@RobinCai1993 I am facing the same issue, could you please share how you fixed it?
Thanks!
