### ISSUE TITLE
Equal probabilities for all the top candidates, answer is always a number of rows @mode=tables ACL2015

### ISSUE THREAD

**Issue by bazhura** [percyliang/sempre#130]
Hi, my goal is to run @mode=tables with learned weights to get interactive answers to custom new questions. First, I tried what's in the tables mode Tutorial: 
`./run @mode=tables -interactive` 
however, it would give me all the same probabilities and pred choices for any of questions in tested table 204-590 http://nlp.stanford.edu/software/sempre/wikitable/viewer/#204-590
```
Pred choices 
  Top formula {
    ((reverse fb:row.row.year) (fb:type.object.type fb:type.row))
  }
  Top value {
    (name fb:cell_year.2003 2003)
    (name fb:cell_year.2002 2002)
    (name fb:cell_year.2001 2001)
    (name fb:cell_year.2007 2007)
    (name fb:cell_year.2006 2006)
    (name fb:cell_year.2005 2005)
    (name fb:cell_year.2004 2004)
    (name fb:cell_year.2009 2009)
    (name fb:cell_year.2008 2008)
    (name fb:cell_year.2010 2010)
    }
```
or the other time is `(number n)`, say `(number 10)`  where `n` is the correct no of rows of that table (tested on different sizes).

My steps:
- built the sempre repo (`./pull-dependencies core corenlp tables tables-data`, etc., compile the source)
- `./run @mode=tables @data=u-1 @feat=all @train=1 -maxex train,100 dev,100`
this gave me exec directory with params (weights) and other files located in `sempre/state/execs/{n}.exec`, let's say n=26
- load params from previously trained weights from that Exec `state/execs/{n}.exec` folder and run interact mode. The resulting answers for the question as above are the same. 

Other modes are working as expected. I managed to run @mode=simple-freebase-nocache as written in the tutorial and get good answers. However, I understand this is different from WebQuestions knowledge base, cannot compare. Please guide me through the process of running trained model for QA, plus whether I have to train it on u-1, u-2, etc. or test splits for the best results?

**Comment by bazhura** [comment]
Just finished another experiment. 

- `./run @mode=tables @data=u-1 @feat=all @train=1 -Parser.beamsize 50`

- `./run @mode=tables -Builder.inParamsPath state/execs/41.exec`

- gave it a context `(context (graph tables.TableKnowledgeGraph csv/204-csv/590.csv))`
and asked two questions from that table. Please see the output here:
[Google Drive](https://drive.google.com/file/d/0B1o0I0WEzbfXcVFGSFZLWEJja2M/view?usp=sharing)

**Comment by ppasupat** [comment]
By default, none of the features are turned on. Try adding `@feat=all` to the second command:
```
./run @mode=tables @train=0 @feat=all -Builder.inParamsPath state/execs/41.exec -interactive
```

**Comment by bazhura** [comment]
It works! Many thanks for your help.
