### ISSUE TITLE
Error running Overnight Parser

### ISSUE THREAD

**Issue by sg1112** [percyliang/sempre#136]
I am trying to Generating canonical utterances by running the given steps. However, I am getting the following error:

```
Value 1 (for key :gen) is invalid; possible values are [0]
Command failed: ./run @mode=genovernight @gen=1 @domain=calendar -execDir genovernight.out/calendar
```

I tried with gen value as 0, I get `Key :pooldir is not in environment ` error.  After which I tried with value of pooldir as 0 and got `Key :parse is not in environment` error. 

Any help!!

**Comment by howcouldyouforgetthisusername** [comment]
Seconding this issue; let me know if you managed to figure it out.

**Comment by ppasupat** [comment]
Will be fixed with https://github.com/percyliang/sempre/pull/156
