### ISSUE TITLE
quesiton about Parsing on Semi-Structured Tables

### ISSUE THREAD

**Issue by hitxujian** [percyliang/sempre#137]
#hi:
I read the code about “Parsing on Semi-Structured Tables”. In a grammar file the original rule is 

**_ori rule_** :     (rule $Operator (how many) (ConstantFn (lambda x (count (var x)))))

after rule analysis, this rule turns into two rules behond
  
                                       
**_changedrule1_**       $Intermediate1      how@many         (ConstantFn null)
**_changedrule2_**       $Operator             $Intermediate1   (ConstantFn (lambda x (count (var x))))

>>but  in the FLoatingParser.java ,in the funciton buildFloating() ,you do some check about the changed rules,about rules rhs ,this means **_changedrule1_** is omitted .why this process? can you give me some explanation ？

  String rhs1 = rule.rhs.get(0);
      String rhs2 = rule.rhs.get(1);
      if (!Rule.isCat(rhs1) || !Rule.isCat(rhs2))
        throw new RuntimeException("Floating rules with > 1 arguments cannot have tokens on the RHS: " + rule);

**Comment by hitxujian** [comment]
if i use parser BeamParser this problem is solved,the former parser is FloatingParser. so the problems is why FloatingParser constrains the rhs of rule must all is category??

**Comment by ppasupat** [comment]
In short, FloatingParser cannot use a BeamParser grammar directly. The file you are using is for BeamParser.

The FloatingParser grammar used in the paper is `tables/grammars/combined.grammar`.

A FloatingParser grammar has 2 types of rules: anchored and floating. Anchored rules are the ones that have `(anchored 1)` at the end, while floating rules don't have `(anchored 1)`. Here is how a FloatingParser works:

1. It creates basic *anchored derivations* from tokens (individual words) and token spans (consecutive words).
2. It applies anchored rules on anchored derivations to create larger anchored derivations.
3. If converts non-basic anchored derivations into floating derivations.
4. It applies floating rules on floating derivations to create larger floating derivations.

Floating rules can only combine floating derivations, and phrases like "how many" are treated as anchored derivations, hence the check fails.

**Comment by hitxujian** [comment]
thanks for answer!

**Comment by hitxujian** [comment]
rule
![image](https://cloud.githubusercontent.com/assets/11830865/25882887/e4abcd2e-3578-11e7-90df-9240f750554c.png)
