### ISSUE TITLE
Easy Setup pre-requisites

### ISSUE THREAD

**Issue by daenenk** [percyliang/sempre#138]
Add make, gcc to the  pre-requisites, or suggest to run `sudo apt install build-essential`
On a ubuntu server distribution this is not standard installed.
Kind regards

**Comment by ppasupat** [comment]
Are these dependencies needed for the main SEMPRE code, or is it just for install virtuoso (Freebase server)?

**Comment by daenenk** [comment]
Already to execute `./pull-dependencies core`
This calls `make -C fig` at line 125.
On a development host `make` is available, but on fresh installed Ubuntu server (without extra packages) it is not.

**Comment by ppasupat** [comment]
Thank you for catching that. I added the dependency to the README file.
