### ISSUE TITLE
Struggling with tutorial exercises

### ISSUE THREAD

**Issue by mseesquared** [percyliang/sempre#14]
I'm having some trouble doing the exercises right not. I've read through the paper that relates to lambda-DCS (http://arxiv.org/pdf/1309.4408v2.pdf) and managed to get `city with the largest area` and  `top 5 cities by area`, but I can't figure out how to get the other phrases that involve more complicated qualifiers, such as `country with the most number of rivers`.

For example, I can get the number of rivers in a given country

`(execute (count (and (fb:type.object.type fb:geography.river (fb:location.location.containedby fb:en.france))))`

and the largest country by area

`(execute (argmax 1 1 (fb:type.object.type fb:location.citytown) fb:location.location.area))`

but I can't figure out how to string these two together to get what I need. Is there another tutorial on lambda-DCS I can look at?

**Comment by kaya27** [comment]
hi,please there is some one who can help me how to use sempre on windows

**Comment by yonatansito** [comment]
Maybe use Cygwin <https://www.cygwin.com/>?
