### ISSUE TITLE
Save training result

### ISSUE THREAD

**Issue by MinseokCho** [percyliang/sempre#142]
I use sempre table version, so i run this model such like './run @mode=tables @data=u-1 @feat=all @train=1'
But training model takes long time, so i want to save training model and test a new question on pre-trained model.
Is it possible? If it is possible, could you tell me how to do it?
Thanks.

**Comment by ppasupat** [comment]
The model is saved in the execution directory (default: `state/execs/___.exec/params`).

To load a saved parameter in a new run, add `-Builder.inParamsPath path/to/params` to the command line.
