### ISSUE TITLE
How to show all values in predicted derivations

### ISSUE THREAD

**Issue by MinseokCho** [percyliang/sempre#144]
Pred@0000: (derivation (formula ((reverse fb:row.row.name) (argmax (number 1) (number 1) (fb:type.object.type fb:type.row) (reverse (lambda r ((reverse fb:cell.cell.number) ((reverse fb:row.row.run) (var r)))))))) ("**5 values**" (name fb:cell_name.denard_span "**Denard Span**")) (type (union fb:column.name fb:type.cell))) [score=41.757, prob=0.735, comp=0]

This is my test result  (before i trained using my training set)

I think that "5 values"  means five cells are duplicated.
But, this model only answer for one answer among duplicated answer.

How can i get output for all 5 duplicate cell value? (not only 1 value ("Denard Span"))
I want to just get duplicated answers for output.

Thank you.

**Comment by ppasupat** [comment]
There are actually 5 different values, but the printout is suppressed to prevent big log files. To turn on the predicted values, add `-Derivation.showValues` to the command line.

**Comment by MinseokCho** [comment]
Thanks for the reply
I
