### ISSUE TITLE
question about lazyL1Update()

### ISSUE THREAD

**Issue by hitxujian** [percyliang/sempre#145]
hi：
the question i ask is about  class Params.java ;

there is a member variable 
public String l1Reg;
when set it to  Params.opts.l1Reg="lazy", then the function lazyL1Update() do some process,what's the intention of lazyl1update do?
can you give some explanation?
thanks!

**Comment by ppasupat** [comment]
It adds L1 regularization to the model. It prevents the parameter weights from being too large and overfitting the training data.

`Params.opts.l1Reg = "nonlazy"` will reduce the sizes of *all* parameter weights for each training example, which takes a lot of time. The `lazy` mode only reduce the sizes of parameters that were accessed in the current example. Its final behavior is the same as `nonlazy`.

The strength of regularization is controlled by `Params.opts.l1RegCoeff`
