### ISSUE TITLE
Installation process enhancement

### ISSUE THREAD

**Issue by JisuPark** [percyliang/sempre#151]
Hello,

As I followed the installation process, I discovered some issues.

1. `zip` is must also be pre-installed.

2. `#!/usr/bin/ruby` doesn't work with ruby environment manager such as [`rbenv`](https://github.com/rbenv/rbenv)
    - Shebang had better change into `#!/usr/bin/env ruby` to follow user's $PATH which makes scripts more portable.

**Comment by JisuPark** [comment]
If you agree with me I'll add `zip` in [`README.md`](https://github.com/percyliang/sempre#requirements).
And change shebang of each of the ruby file i) [`run`](https://github.com/percyliang/sempre/blob/master/run) and ii) [`scripts/extract-module-classes.rb`](https://github.com/percyliang/sempre/blob/master/scripts/extract-module-classes.rb)

**Comment by ppasupat** [comment]
Sounds good to me. Thank you!
