### ISSUE TITLE
Unable to Reproduce Overnight Canonical Utterances

### ISSUE THREAD

**Issue by howcouldyouforgetthisusername** [percyliang/sempre#155]
When I run in genovernight mode, SEMPRE doesn't actually produce any canonical utterances. If I understand the log output correctly, it seems that it doesn't know about the general grammar. Or at least, it doesn't know about `$BinaryOp` or `$Rel0NP`. Here is a representative log file, along with the output grammar. Let me know if you have any ideas! Thanks.

[log.txt](https://github.com/percyliang/sempre/files/1264801/log.txt)
[grammar.txt](https://github.com/percyliang/sempre/files/1264831/grammar.txt)

**Comment by percyliang** [comment]
The results from the overnight paper are available on CodaLab:
https://worksheets.codalab.org/worksheets/0x269ef752f8c344a28383240f7bb2be9c/
The master branch is not guaranteed to reproduce the results.

**Comment by howcouldyouforgetthisusername** [comment]
Thanks Percy!

**Comment by howcouldyouforgetthisusername** [comment]
I've tried pulling from master then replacing every file/directory with the corresponding files from the CodaLab worksheet, but I continue to get the same problems.

After some further digging on CodaLab, I realized that your runs always got the same complaints about $BinaryOp's and $Rel0NP, which convinced me that wasn't the actual problem. With a liberal application of print statements, it seems that predDerivations never gets anything added to it, and that may be due to encountering the following:
`Exception in thread "Thread-1" java.lang.RuntimeException: Floating rules with > 1 arguments cannot have tokens on the RHS: $Intermediate1 -> that $VP (SelectFn 0)`

Let me know if you have any recommendations; I really appreciate the help.

**Comment by yonatansito** [comment]
Hi,
Not sure what exactly you tried to do but the two categories $BinaryOp and $Rel0NP don't appear in all datasets (just in one I think) - so if you tried generating from most overnight datasets indeed the lexicon does not contain any word mapped to these categories and that is fine...

**Comment by ppasupat** [comment]
I think that's my fault. I assumed that RHS of floating rules will not have non-categories, so I added that check. I put it back in and made a pull request.

**Comment by ppasupat** [comment]
https://github.com/percyliang/sempre/pull/156
