### ISSUE TITLE
unknown option while running overnight sample for publications

### ISSUE THREAD

**Issue by BrijeshKaria** [percyliang/sempre#164]
I am not able to figure out how i resolve this error - "Unknown option: 'overnightderivationpruningcomputer.applyhardconstraints';"

I am trying to run subset of features for ablation studies
command
./run @mode=overnight @domain=publications -OvernightFeatureComputer.featureDomains match skip-bigram root lf simpleworld

please advice.

**Comment by ppasupat** [comment]
Try removing the line `o('OvernightDerivationPruningComputer.applyHardConstraints')` in the `run` script (Line 554).

**Comment by BrijeshKaria** [comment]
Able to proceed after making this change.
