### ISSUE TITLE
java.lang.IndexOutOfBoundsException while running overnight samples

### ISSUE THREAD

**Issue by BrijeshKaria** [percyliang/sempre#165]
I tried running theovernight samples for 2 domains - publication and geo880 and i get below error in both cases.

geo880
======

ParserState.pruneCell $NP2:7: maxCellSize = 7440 entries (not pruned yet)
                **ERROR: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0:
java.util.ArrayList.rangeCheck(ArrayList.java:657)**
java.util.ArrayList.get(ArrayList.java:433)
edu.stanford.nlp.sempre.overnight.OvernightFeatureComputer.extractRootFeatures(OvernightFeatureComputer.java:185)
edu.stanford.nlp.sempre.overnight.OvernightFeatureComputer.extractLocal(OvernightFeatureComputer.java:70)
edu.stanford.nlp.sempre.FeatureExtractor.extractLocal(FeatureExtractor.java:71)
edu.stanford.nlp.sempre.ParserState.featurizeAndScoreDerivation(ParserState.java:74)
edu.stanford.nlp.sempre.FloatingParserState.addToChart(FloatingParser.java:208)
edu.stanford.nlp.sempre.FloatingParserState.applyRuleActual(FloatingParser.java:266)
edu.stanford.nlp.sempre.FloatingParserState.applyRule(FloatingParser.java:222)
edu.stanford.nlp.sempre.FloatingParserState.applyFloatingRule(FloatingParser.java:277)
edu.stanford.nlp.sempre.FloatingParserState.buildFloating(FloatingParser.java:460)
edu.stanford.nlp.sempre.FloatingParserState.access$500(FloatingParser.java:170)
edu.stanford.nlp.sempre.FloatingParserState$DerivationBuilder.run(FloatingParser.java:507)
edu.stanford.nlp.sempre.FloatingParserState.buildDerivations(FloatingParser.java:543)
edu.stanford.nlp.sempre.FloatingParserState.infer(FloatingParser.java:572)
edu.stanford.nlp.sempre.Parser.parse(Parser.java:170)
edu.stanford.nlp.sempre.Learner.parseExample(Learner.java:288)
edu.stanford.nlp.sempre.Learner.processExamples(Learner.java:199)
edu.stanford.nlp.sempre.Learner.learn(Learner.java:125)
edu.stanford.nlp.sempre.Learner.learn(Learner.java:90)
edu.stanford.nlp.sempre.Main.run(Main.java:27)
fig.exec.Execution.runWithObjArray(Execution.java:337)
fig.exec.Execution.run(Execution.java:325)
edu.stanford.nlp.sempre.Main.main(Main.java:50)

publications
==========

Loading ppdb model {
                  ParaphraseUtils.loadPhraseTable: number of entries=2149
                }
                **ERROR: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0:
java.util.ArrayList.rangeCheck(ArrayList.java:657)**
java.util.ArrayList.get(ArrayList.java:433)
edu.stanford.nlp.sempre.overnight.OvernightFeatureComputer.extractRootFeatures(OvernightFeatureComputer.java:185)
edu.stanford.nlp.sempre.overnight.OvernightFeatureComputer.extractLocal(OvernightFeatureComputer.java:70)
edu.stanford.nlp.sempre.FeatureExtractor.extractLocal(FeatureExtractor.java:71)
edu.stanford.nlp.sempre.ParserState.featurizeAndScoreDerivation(ParserState.java:74)
edu.stanford.nlp.sempre.FloatingParserState.addToChart(FloatingParser.java:208)
edu.stanford.nlp.sempre.FloatingParserState.applyRuleActual(FloatingParser.java:266)
edu.stanford.nlp.sempre.FloatingParserState.applyRule(FloatingParser.java:222)
edu.stanford.nlp.sempre.FloatingParserState.applyFloatingRule(FloatingParser.java:277)
edu.stanford.nlp.sempre.FloatingParserState.buildFloating(FloatingParser.java:460)
edu.stanford.nlp.sempre.FloatingParserState.access$500(FloatingParser.java:170)
edu.stanford.nlp.sempre.FloatingParserState$DerivationBuilder.run(FloatingParser.java:507)
edu.stanford.nlp.sempre.FloatingParserState.buildDerivations(FloatingParser.java:543)
edu.stanford.nlp.sempre.FloatingParserState.infer(FloatingParser.java:572)
edu.stanford.nlp.sempre.Parser.parse(Parser.java:170)
edu.stanford.nlp.sempre.Learner.parseExample(Learner.java:288)
edu.stanford.nlp.sempre.Learner.processExamples(Learner.java:199)
edu.stanford.nlp.sempre.Learner.learn(Learner.java:125)
edu.stanford.nlp.sempre.Learner.learn(Learner.java:90)
edu.stanford.nlp.sempre.Main.run(Main.java:27)
fig.exec.Execution.runWithObjArray(Execution.java:337)
fig.exec.Execution.run(Execution.java:325)
edu.stanford.nlp.sempre.Main.main(Main.java:50)

Please advice how can i go about debugging this.

Thanks.

**Comment by ppasupat** [comment]
It turns out that the line
```
o('OvernightDerivationPruningComputer.applyHardConstraints')
```
in the `run` file has to be *replaced* with the new option syntax
```
o('DerivationPruner.pruningStrategies', ['violateHardConstraints'])
```

I will push the fix soon.

**Comment by ppasupat** [comment]
I pushed the new run file. Can you try it?

**Comment by BrijeshKaria** [comment]
Changes to the run file worked fine.
Thanks!
