### ISSUE TITLE
cannot find symbol - javac error 

### ISSUE THREAD

**Issue by erastogi** [percyliang/sempre#170]
I am getting following errors when I execute ant core :
![smpre](https://user-images.githubusercontent.com/24869756/35298915-9f0f9c6a-0051-11e8-8db6-fedd87e4c4fb.png)

**Comment by ppasupat** [comment]
Looks like the dependencies are missing. Could you try running:
```
./pull-dependencies core
ant clean
ant core
```

**Comment by erastogi** [comment]
I get the same error as above

**Comment by ppasupat** [comment]
Could you try removing the `lib` directory and repeat the process above. If there is any error while running `./pull-dependencies core`, please note it here.

**Comment by erastogi** [comment]
Thanks, it's running now.
