### ISSUE TITLE
Code to Interpret Sempre Grammar

### ISSUE THREAD

**Issue by rktamplayo** [percyliang/sempre#171]
I ran the code and got results in a form like this:

(derivation (formula (min ((reverse fb:cell.cell.number) ((reverse fb:row.row.gf) (argmin (number 1) (number 1) (fb:type.object.type fb:type.row) (reverse (lambda r ((reverse fb:cell.cell.number) ((reverse fb:row.row.pk) (var r)))))))))) ("1 values" (number 0)) (type fb:type.number))

I have a table and would like to know the step-by-step result of the query above.

For example, from the query above, I would like to know which cells are used as conditions (i.e. cells in column pk where the value is the minimum), which cells are selected (i.e. corresponding gf cells), and finally which cell is the final answer (i.e. the minimum among the gf cells).

I can read code, but it is hard for me to sift out which part of the enormous project should I scan to do this task. Is there a quick code to do this? If not, which class/es and method/s should I look at?

Thanks!

**Comment by ppasupat** [comment]
The code for executing such logical forms is located in the `src.edu.stanford.nlp.sempre.tables.lambdadcs` package. The main executor is `LambdaDCSExecutor`. Unfortunately, the code is pretty complicated.

Here's a summary of how the mentioned logical form executes:

- The innermost part is `(argmin ...)`, which computes argmin of a function over some set (returning the set element with the minimum function value).
  - The two `(number 1)` means "returning 1 result from the 1st rank". If there is a tie, return all tying results.
  - The next argument indicates the set. `(fb:type.object.type fb:type.row)` is the list of all objects of type `row`.
  - The final argument indicates the function. `(lambda r ((reverse fb:cell.cell.number) ((reverse fb:row.row.pk) (var r))))` is a function that takes a row `r` and applies two relations
    - `(reverse fb:row.row.pk)` is the row-cell relation relating a row to the cell in the `pk` column of that row. The default direction is cell to row; the `reverse` switches the direction so that it takes a row and returns a cell instead
    - `(reverse fb:cell.cell.number)` is the cell-value relation relating a cell to the numerical value of the cell.
  - Therefore, this whole argmin returns rows whose the numerical value in the `pk` column is the lowest. This can return a set of multiple rows if there is a tie.
- The resulting rows are then applied with relation `(reverse fb:row.row.gf)`, which takes each row and returns the cell in the `gf` column.
- `(reverse fb:cell.cell.number)` takes each cell and returns the numerical value in that cell.
- Finally, `min` computes the minimum of the resulting values.
