### ISSUE TITLE
Can the model from online/batch learning be saved after restart sempre?

### ISSUE THREAD

**Issue by matchgirl** [percyliang/sempre#172]
After we restart sempre interactive mode, score which it learned last time cannot be kept.  Do we have any way to do this? thanks alot!

**Comment by ppasupat** [comment]
Just to confirm, this is the interactive mode invoked by `-interactive`, right?

Could you try using the `(params /path/to/filename)` command in the interactive prompt? This should save the parameters to the specified filename.

Then to load it in a new session, add `-params.inpath /path/to/filename` to the command line
