### ISSUE TITLE
Doubt regarding semantic parsing

### ISSUE THREAD

**Issue by bhi5hmaraj** [percyliang/sempre#175]
For my question answering project , I need to extract certain entities like name, location, organisation , etc and create a query out of it . The recognition part can be done by training a custom NER using Stanford's corenlp. The doubt I have is if my intent is narrow , then is it required to write a grammar and create the semantics  ? Can't I just create the semantics for a question by just checking if it has so and so entities and directly create one. For example , let's say my query is "who knows John Doe from New York" , then I can just create a semantic by just recognising the named entities . More precisely can't I train a classifier on annotated questions and then use it for classifying my utterance . Suppose I have 2 different types of questions , one regarding people and one regarding  company. Now I can train a classifier to classify between these 2 classes and then use that to create a query.

Is creating a grammar overkill here ?

**Comment by ppasupat** [comment]
If there are only 2 different types of questions, with all NERs detected, writing a grammar might be an overkill. A simple classifier might just suffice.

**Comment by bhi5hmaraj** [comment]
Thanks a lot for your response. The whole Stanford "suite" for NLP (CoreNLP, sippycup, SEMPRE,  the archived Coursera course by Jurafsky and Manning) has been super helpful for my project. I don't know how to thank you guys !

The problem I'm facing is that due to the narrow nature of my project , I wasn't able to find any existing data-sets. So I had to start making my own. Right now I have around 300 questions (2 main classes and 1 discriminatory class which distinguishes the question from the other 2 classes). This is making both my NER and my overall question intent classifier to highly over-fit. Is there a better and faster way to get more questions for training and testing ?

I was [suggested](https://www.facebook.com/groups/idliai/permalink/2020608907956994/) to look at distant supervision. I was able to find its usage for relationship extraction . Could it be modified in some way to generate questions from relationship tuples ?

**Comment by ppasupat** [comment]
- Try using the pre-trained NER model, which was trained on a lot more data.
- It's a little strange that a 2-class classifier would highly overfit. What kind of classifier did you use? How much sentence variability do you have?

**Comment by ppasupat** [comment]
Also, it would be great if you can post some example sentences. SEMPRE is in some sense a classifier, and could potentially be used to handle your task.

**Comment by bhi5hmaraj** [comment]
Due to the nature of the problem , I've mailed you the details. I would be glad if we could continue the discussion over mail.
