### ISSUE TITLE
Sempre Tables code not running

### ISSUE THREAD

**Issue by SaiKeshav** [percyliang/sempre#176]
This is to inform an issue that I found with [tables](https://github.com/percyliang/sempre/tree/master/tables) code. It compiles fine but raises the following error while running:  

Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: edu.stanford.nlp.sempre.cprune.CPruneDerivInfo

However, it works if I also compile, 
`ant cprune`

Could you correct the build.xml or add this to the [tables](https://github.com/percyliang/sempre/tree/master/tables) instructions, so that it will be helpful for others who may try to run it.

**Comment by ppasupat** [comment]
Thank you for reporting.
#177

**Comment by ppasupat** [comment]
Would you mind checking if the new build file works as expected? Thank you.

**Comment by SaiKeshav** [comment]
Sorry for my delayed response. The build file is working as expected. Thanks for fixing it!
