### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by B417037** [percyliang/sempre#190]
After cloning it, I am not able to execute the command "./pull-dependencies core" it shows an error as "." is not recognized as an internal or external command. I am using java 8 and ant version 1.10.5. I even tried to change to .\ but got the same error. Also I tried to add a semicolon at the end of PATH variable in the Environment variable but of no use.

**Comment by B417037** [comment]
C:/Users/Sakshi Sharma/Documents/GitHub/sempre/fig/lib/myutils.rb:389:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
I am actually getting a fork implementation error for that.

**Comment by ppasupat** [comment]
Here's a potential workaround:

* When running the `run` command, add `-n` to the end. This will print out the equivalent Java command and then exit.
* Run the Java command shown.

**Comment by B417037** [comment]
Thank a lot for your help. Actually, I am still not able to get it. The output is something like this-->
C:\Users\Sakshi Sharma\Documents\GitHub\sempre>ruby run @mode=simple -n
java -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive

C:\Users\Sakshi Sharma\Documents\GitHub\sempre>java -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive
Error: Could not find or load main class edu.stanford.nlp.sempre.Main

Any suggestions?

**Comment by ppasupat** [comment]
Are there jar files in the `libsempre` directory? If not, run `ant` first.

Another thing to try is changing `/` to `\`.

**Comment by B417037** [comment]
I am getting the same error. I ran 
ant clean
ruby pull-dependencies core
ruby pull-dependencies corenlp 
ant core corenlp
java -cp libsempre/:lib/ -ea edu.stanford.nlp.sempre.Main -Main.interactive
same error.

**Comment by ppasupat** [comment]
> java -cp libsempre/:lib/ -ea edu.stanford.nlp.sempre.Main -Main.interactive

Could you try changing `libsempre/:lib/` to `libsempre\:lib\` or `C:\.....(full path to this directory)....\libsempre\:C:\.....(full path to this directory)....\lib\`

**Comment by B417037** [comment]
I was getting the same error for that as well.
So I dual boot ubuntu on my pc. Now it's working!! I guess it has some issues with windows.
Thanks a lot for your help.
