### ISSUE TITLE
Command failed: fig/bin/qcreate

### ISSUE THREAD

**Issue by afader** [percyliang/sempre#2]
(I figured I'd post here instead of emailing in case others have the same problem.)

Hey guys, I'm trying to train the WebQuestions system from your EMNLP paper. I've downloaded the freebase files and started the virtuoso server, but when I run 

```
./sempre @mode=train @sparqlserver=localhost:3001 @domain=webquestions @cacheserver=local
```

I get the error `./fig/lib/myutils.rb:389:in`exec': No such file or directory - fig/bin/qcreate (Errno::ENOENT)`. Full output is here: https://gist.github.com/afader/7275339

I can't find qcreate anywhere in the project. Any idea what's going on?

**Comment by mmarinated** [comment]
I'm trying to run overnight, but I'm getting the same error:
`$ ./run @mode=genovernight-wrapper`

`/home/marina/sempre/fig/lib/myutils.rb:389:in 'exec': No such file or directory - fig/bin/qcreate (Errno::ENOENT)`

Though I checked, and this file exists. 
Did anyone have this issue?

**Comment by ppasupat** [comment]
That's strange. In the base directory, could you try reloading fig:
```
rm -rf fig
./pull-dependencies fig
```
And could you try running ```./fig/bin/qcreate``` and see what it says?

**Comment by mmarinated** [comment]
I reloaded it, but it's the same error I am getting. I attach the txt file with the ouput.
[error_fig_bin_qcreate.txt](https://github.com/percyliang/sempre/files/3091147/error_fig_bin_qcreate.txt)

If I run `./fig/bin/qcreate`, I'm getting `bash: ./fig/bin/qcreate: /usr/bin/ruby: bad interpreter: No such file or directory`. Though command `ls ./fig/bin/` shows `qcreate` in the list.

**Comment by ppasupat** [comment]
Could you check if ruby is installed on your machine, and is callable at `/usr/bin/ruby`? The fig scripts were developed under ruby 1.8.7 or 1.9, but more recent versions should also work.

To check, run
```
type ruby
ruby --version
```

**Comment by mmarinated** [comment]
The version is `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]`. 
Ruby is at `#!/home/marina/.conda/envs/java_env/bin/ruby`. I changed all ruby files and put this path, but the error is the same.

**Comment by ppasupat** [comment]
Could you try changing the first lines of all ruby files in `fig/bin` to
```
#!/usr/bin/env ruby
```
and copy the output of calling `./fig/bin/qcreate` here?

Maybe try running `ruby` to check if `/usr/bin/env ruby` invokes the right ruby:
```
/usr/bin/env ruby
puts 2 + 2
```
then press ctrl+d. The result should be 4.

**Comment by mmarinated** [comment]
It works!
Thank you very much for help!
