### ISSUE TITLE
Trouble with "ant freebase"

### ISSUE THREAD

**Issue by mr-asleep** [percyliang/sempre#201]
Here is the compile error output when ant freebase is used . Please resolve . Thanks in advance
Buildfile: /home/ritik/rashi/build.xml

init:
     [exec] Wrote modules with 328 files to module-classes.txt: cache core corenlp cprune freebase geo880 interactive overnight tables

core:
     [echo] Compiling semparse: core
    [javac] Compiling 134 source files to /home/ritik/rashi/classes
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
      [jar] Building jar: /home/ritik/rashi/libsempre/sempre-core.jar

cache:
     [echo] Compiling semparse: cache
    [mkdir] Created dir: /home/ritik/rashi/classes/cache
    [javac] Compiling 8 source files to /home/ritik/rashi/classes/cache
      [jar] Building jar: /home/ritik/rashi/libsempre/sempre-cache.jar

freebase:
     [echo] Compiling semparse: freebase
    [mkdir] Created dir: /home/ritik/rashi/classes/freebase
    [javac] Compiling 55 source files to /home/ritik/rashi/classes/freebase
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/BinaryLexicon.java:4: error: package edu.stanford.nlp.io does not exist
    [javac] import edu.stanford.nlp.io.IOUtils;
    [javac]                           ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/FbFormulasInfo.java:4: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.ClassicCounter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/FbFormulasInfo.java:5: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.Counter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/LexicalEntry.java:9: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.ClassicCounter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/LexicalEntry.java:10: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.Counter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/LexicalEntry.java:11: error: package edu.stanford.nlp.util does not exist
    [javac] import edu.stanford.nlp.util.StringUtils;
    [javac]                             ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/TextToTextMatcher.java:5: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.ClassicCounter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/TextToTextMatcher.java:6: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.Counter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/TextToTextMatcher.java:7: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.Counters;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/Stemmer.java:3: error: package org.tartarus.snowball.ext does not exist
    [javac] import org.tartarus.snowball.ext.PorterStemmer;
    [javac]                                 ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/TextToTextMatcher.java:126: error: cannot find symbol
    [javac]   private void addFeaturesToVector(Counter<String> features, String prefix, FeatureVector vector) {
    [javac]                                    ^
    [javac]   symbol:   class Counter
    [javac]   location: class TextToTextMatcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/EntityLexicon.java:3: error: package edu.stanford.nlp.io does not exist
    [javac] import edu.stanford.nlp.io.IOUtils;
    [javac]                           ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/EntityLexicon.java:14: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.Counter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/EntityLexicon.java:15: error: package edu.stanford.nlp.util does not exist
    [javac] import edu.stanford.nlp.util.ArrayUtils;
    [javac]                             ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/EntityLexicon.java:16: error: package edu.stanford.nlp.util does not exist
    [javac] import edu.stanford.nlp.util.StringUtils;
    [javac]                             ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/EntityLexicon.java:19: error: package org.apache.lucene.document does not exist
    [javac] import org.apache.lucene.document.Document;
    [javac]                                  ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/EntityLexicon.java:20: error: package org.apache.lucene.queryparser.classic does not exist
    [javac] import org.apache.lucene.queryparser.classic.ParseException;
    [javac]                                             ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:5: error: package org.apache.lucene.analysis.core does not exist
    [javac] import org.apache.lucene.analysis.core.KeywordAnalyzer;
    [javac]                                       ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:6: error: package org.apache.lucene.analysis.standard does not exist
    [javac] import org.apache.lucene.analysis.standard.StandardAnalyzer;
    [javac]                                           ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:7: error: package org.apache.lucene.document does not exist
    [javac] import org.apache.lucene.document.Document;
    [javac]                                  ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:8: error: package org.apache.lucene.index does not exist
    [javac] import org.apache.lucene.index.DirectoryReader;
    [javac]                               ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:9: error: package org.apache.lucene.index does not exist
    [javac] import org.apache.lucene.index.IndexReader;
    [javac]                               ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:10: error: package org.apache.lucene.queryparser.classic does not exist
    [javac] import org.apache.lucene.queryparser.classic.ParseException;
    [javac]                                             ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:11: error: package org.apache.lucene.queryparser.classic does not exist
    [javac] import org.apache.lucene.queryparser.classic.QueryParser;
    [javac]                                             ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:12: error: package org.apache.lucene.search does not exist
    [javac] import org.apache.lucene.search.IndexSearcher;
    [javac]                                ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:13: error: package org.apache.lucene.search does not exist
    [javac] import org.apache.lucene.search.Query;
    [javac]                                ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:14: error: package org.apache.lucene.search does not exist
    [javac] import org.apache.lucene.search.ScoreDoc;
    [javac]                                ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:15: error: package org.apache.lucene.store does not exist
    [javac] import org.apache.lucene.store.SimpleFSDirectory;
    [javac]                               ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:16: error: package org.apache.lucene.util does not exist
    [javac] import org.apache.lucene.util.Version;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/EntityLexicon.java:64: error: cannot find symbol
    [javac]   public List<EntityLexicalEntry> lookupEntries(String query, SearchStrategy strategy) throws ParseException, IOException {
    [javac]                                                                                               ^
    [javac]   symbol:   class ParseException
    [javac]   location: class EntityLexicon
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/EntityLexicon.java:122: error: cannot find symbol
    [javac]   public List<EntityLexicalEntry> lookupEntries(FbEntitySearcher searcher, String textDesc) throws ParseException, IOException {
    [javac]                                                                                                    ^
    [javac]   symbol:   class ParseException
    [javac]   location: class EntityLexicon
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:28: error: cannot find symbol
    [javac]   private final QueryParser queryParser;
    [javac]                 ^
    [javac]   symbol:   class QueryParser
    [javac]   location: class FbEntitySearcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:29: error: cannot find symbol
    [javac]   private final IndexSearcher indexSearcher;
    [javac]                 ^
    [javac]   symbol:   class IndexSearcher
    [javac]   location: class FbEntitySearcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:53: error: cannot find symbol
    [javac]   public synchronized List<Document> searchDocs(String question) throws IOException, ParseException {
    [javac]                            ^
    [javac]   symbol:   class Document
    [javac]   location: class FbEntitySearcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:53: error: cannot find symbol
    [javac]   public synchronized List<Document> searchDocs(String question) throws IOException, ParseException {
    [javac]                                                                                      ^
    [javac]   symbol:   class ParseException
    [javac]   location: class FbEntitySearcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:69: error: cannot find symbol
    [javac]   private ScoreDoc[] getHits(String question) throws IOException, ParseException {
    [javac]           ^
    [javac]   symbol:   class ScoreDoc
    [javac]   location: class FbEntitySearcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:69: error: cannot find symbol
    [javac]   private ScoreDoc[] getHits(String question) throws IOException, ParseException {
    [javac]                                                                   ^
    [javac]   symbol:   class ParseException
    [javac]   location: class FbEntitySearcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntitySearcher.java:75: error: cannot find symbol
    [javac]   public static void main(String[] args) throws IOException, ParseException {
    [javac]                                                              ^
    [javac]   symbol:   class ParseException
    [javac]   location: class FbEntitySearcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/LexicalEntry.java:187: error: cannot find symbol
    [javac]     public Counter<String> entityFeatures;
    [javac]            ^
    [javac]   symbol:   class Counter
    [javac]   location: class EntityLexicalEntry
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/LexicalEntry.java:191: error: cannot find symbol
    [javac]                               Counter<String> entityFeatures) {
    [javac]                               ^
    [javac]   symbol:   class Counter
    [javac]   location: class EntityLexicalEntry
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/FbFormulasInfo.java:352: error: cannot find symbol
    [javac]     private Counter<Formula> fCounter;
    [javac]             ^
    [javac]   symbol:   class Counter
    [javac]   location: class FbFormulasInfo.FormulaByCounterComparator
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/FbFormulasInfo.java:354: error: cannot find symbol
    [javac]     public FormulaByCounterComparator(Counter<Formula> fCounter) {
    [javac]                                       ^
    [javac]   symbol:   class Counter
    [javac]   location: class FbFormulasInfo.FormulaByCounterComparator
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/Free917Converter.java:3: error: package edu.stanford.nlp.io does not exist
    [javac] import edu.stanford.nlp.io.IOUtils;
    [javac]                           ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/Free917Converter.java:9: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.ClassicCounter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/Free917Converter.java:10: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.Counter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/Free917Converter.java:11: error: package edu.stanford.nlp.util does not exist
    [javac] import edu.stanford.nlp.util.StringUtils;
    [javac]                             ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/Free917Converter.java:30: error: cannot find symbol
    [javac]   private Counter<Integer> argnumCounter = new ClassicCounter<Integer>();
    [javac]           ^
    [javac]   symbol:   class Counter
    [javac]   location: class Free917Converter
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/Lexicon.java:10: error: package org.apache.lucene.queryparser.classic does not exist
    [javac] import org.apache.lucene.queryparser.classic.ParseException;
    [javac]                                             ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/UnaryLexicon.java:4: error: package edu.stanford.nlp.io does not exist
    [javac] import edu.stanford.nlp.io.IOUtils;
    [javac]                           ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/Lexicon.java:62: error: cannot find symbol
    [javac]   public List<? extends LexicalEntry> lookupEntities(String query, EntityLexicon.SearchStrategy strategy) throws IOException, ParseException {
    [javac]                                                                                                                               ^
    [javac]   symbol:   class ParseException
    [javac]   location: class Lexicon
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/LexiconFn.java:8: error: package org.apache.lucene.queryparser.classic does not exist
    [javac] import org.apache.lucene.queryparser.classic.ParseException;
    [javac]                                             ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntityIndexer.java:3: error: package edu.stanford.nlp.io does not exist
    [javac] import edu.stanford.nlp.io.IOUtils;
    [javac]                           ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntityIndexer.java:5: error: package org.apache.lucene.analysis.core does not exist
    [javac] import org.apache.lucene.analysis.core.KeywordAnalyzer;
    [javac]                                       ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntityIndexer.java:6: error: package org.apache.lucene.analysis.standard does not exist
    [javac] import org.apache.lucene.analysis.standard.StandardAnalyzer;
    [javac]                                           ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntityIndexer.java:7: error: package org.apache.lucene.document does not exist
    [javac] import org.apache.lucene.document.*;
    [javac] ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntityIndexer.java:8: error: package org.apache.lucene.index does not exist
    [javac] import org.apache.lucene.index.IndexWriter;
    [javac]                               ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntityIndexer.java:9: error: package org.apache.lucene.index does not exist
    [javac] import org.apache.lucene.index.IndexWriterConfig;
    [javac]                               ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntityIndexer.java:10: error: package org.apache.lucene.index.IndexWriterConfig does not exist
    [javac] import org.apache.lucene.index.IndexWriterConfig.OpenMode;
    [javac]                                                 ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntityIndexer.java:11: error: package org.apache.lucene.store does not exist
    [javac] import org.apache.lucene.store.SimpleFSDirectory;
    [javac]                               ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntityIndexer.java:12: error: package org.apache.lucene.util does not exist
    [javac] import org.apache.lucene.util.Version;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/index/FbEntityIndexer.java:20: error: cannot find symbol
    [javac]   private final IndexWriter indexer;
    [javac]                 ^
    [javac]   symbol:   class IndexWriter
    [javac]   location: class FbEntityIndexer
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/LexicalEntry.java:251: error: cannot find symbol
    [javac]     static Counter<String> counterFromLispTree(LispTree tree) {
    [javac]            ^
    [javac]   symbol:   class Counter
    [javac]   location: class LexicalEntrySerializer
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/LexicalEntry.java:257: error: cannot find symbol
    [javac]     static LispTree counterToLispTree(Counter<String> counter) {
    [javac]                                       ^
    [javac]   symbol:   class Counter
    [javac]   location: class LexicalEntrySerializer
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/TokenLevelMatchFeatures.java:4: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.ClassicCounter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/TokenLevelMatchFeatures.java:5: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.Counter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/TokenLevelMatchFeatures.java:36: error: cannot find symbol
    [javac]   public static Counter<String> extractFeatures(String query, String answer) {
    [javac]                 ^
    [javac]   symbol:   class Counter
    [javac]   location: class TokenLevelMatchFeatures
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/TokenLevelMatchFeatures.java:181: error: cannot find symbol
    [javac]   public static Counter<String> extractTokenMatchFeatures(List<String> source, List<String> target, boolean strict) {
    [javac]                 ^
    [javac]   symbol:   class Counter
    [javac]   location: class TokenLevelMatchFeatures
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/normalizers/BinaryNormalizer.java:3: error: package edu.stanford.nlp.util does not exist
    [javac] import edu.stanford.nlp.util.ArrayUtils;
    [javac]                             ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/normalizers/PrepDropNormalizer.java:3: error: package edu.stanford.nlp.util does not exist
    [javac] import edu.stanford.nlp.util.ArrayUtils;
    [javac]                             ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/test/TokenMatchTest.java:4: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.Counter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/FileUtils.java:6: error: package edu.stanford.nlp.io does not exist
    [javac] import edu.stanford.nlp.io.IOUtils;
    [javac]                           ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/FileUtils.java:7: error: package edu.stanford.nlp.objectbank does not exist
    [javac] import edu.stanford.nlp.objectbank.ObjectBank;
    [javac]                                   ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/FileUtils.java:12: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.ClassicCounter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/FileUtils.java:13: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.Counter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/FileUtils.java:14: error: package edu.stanford.nlp.util does not exist
    [javac] import edu.stanford.nlp.util.StringUtils;
    [javac]                             ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/FileUtils.java:180: error: cannot find symbol
    [javac]   public static Counter<String> loadStringCounter(String filename) {
    [javac]                 ^
    [javac]   symbol:   class Counter
    [javac]   location: class FileUtils
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/FreebaseUtils.java:5: error: package edu.stanford.nlp.io does not exist
    [javac] import edu.stanford.nlp.io.IOUtils;
    [javac]                           ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/LinkedExtractionFileUtils.java:3: error: package edu.stanford.nlp.io does not exist
    [javac] import edu.stanford.nlp.io.IOUtils;
    [javac]                           ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/MathUtils.java:3: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.ClassicCounter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/MathUtils.java:4: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.Counter;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/MathUtils.java:5: error: package edu.stanford.nlp.stats does not exist
    [javac] import edu.stanford.nlp.stats.Counters;
    [javac]                              ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/MathUtils.java:19: error: cannot find symbol
    [javac]   public static <E> double generalizedJensenShannonDivergence(Counter<E> c1, Counter<E> c2) {
    [javac]                                                               ^
    [javac]   symbol:   class Counter
    [javac]   location: class MathUtils
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/MathUtils.java:19: error: cannot find symbol
    [javac]   public static <E> double generalizedJensenShannonDivergence(Counter<E> c1, Counter<E> c2) {
    [javac]                                                                              ^
    [javac]   symbol:   class Counter
    [javac]   location: class MathUtils
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/MathUtils.java:46: error: cannot find symbol
    [javac]   public static Counter<String> prefixCounterKeys(Counter<String> counter, String prefix) {
    [javac]                                                   ^
    [javac]   symbol:   class Counter
    [javac]   location: class MathUtils
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/MathUtils.java:46: error: cannot find symbol
    [javac]   public static Counter<String> prefixCounterKeys(Counter<String> counter, String prefix) {
    [javac]                 ^
    [javac]   symbol:   class Counter
    [javac]   location: class MathUtils
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/SemparseLogTools.java:3: error: package edu.stanford.nlp.io does not exist
    [javac] import edu.stanford.nlp.io.IOUtils;
    [javac]                           ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/WordNet.java:28: error: package edu.stanford.nlp.io does not exist
    [javac] import edu.stanford.nlp.io.RuntimeIOException;
    [javac]                           ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/utils/WordNet.java:29: error: package edu.stanford.nlp.objectbank does not exist
    [javac] import edu.stanford.nlp.objectbank.ObjectBank;
    [javac]                                   ^
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/FbFormulasInfo.java:343: error: cannot find symbol
    [javac]     Counter<Formula> counter = new ClassicCounter<>();
    [javac]     ^
    [javac]   symbol:   class Counter
    [javac]   location: class FbFormulasInfo
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/FbFormulasInfo.java:343: error: cannot find symbol
    [javac]     Counter<Formula> counter = new ClassicCounter<>();
    [javac]                                    ^
    [javac]   symbol:   class ClassicCounter
    [javac]   location: class FbFormulasInfo
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/LexicalEntry.java:69: error: cannot find symbol
    [javac]       int currDistance = StringUtils.editDistance(query, description.toLowerCase());
    [javac]                          ^
    [javac]   symbol:   variable StringUtils
    [javac]   location: class LexicalEntry
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/LexicalEntry.java:252: error: cannot find symbol
    [javac]       Counter<String> counter = new ClassicCounter<String>();
    [javac]       ^
    [javac]   symbol:   class Counter
    [javac]   location: class LexicalEntrySerializer
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/LexicalEntry.java:252: error: cannot find symbol
    [javac]       Counter<String> counter = new ClassicCounter<String>();
    [javac]                                     ^
    [javac]   symbol:   class ClassicCounter
    [javac]   location: class LexicalEntrySerializer
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/lexicons/LexicalEntry.java:317: error: cannot find symbol
    [javac]         Counter<String> tokenEditDistanceFeatures = counterFromLispTree(tree.child(i++));
    [javac]         ^
    [javac]   symbol:   class Counter
    [javac]   location: class LexicalEntrySerializer
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/TextToTextMatcher.java:82: error: cannot find symbol
    [javac]     Counter<String> tokenFeatures = new ClassicCounter<String>();
    [javac]     ^
    [javac]   symbol:   class Counter
    [javac]   location: class TextToTextMatcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/TextToTextMatcher.java:82: error: cannot find symbol
    [javac]     Counter<String> tokenFeatures = new ClassicCounter<String>();
    [javac]                                         ^
    [javac]   symbol:   class ClassicCounter
    [javac]   location: class TextToTextMatcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/TextToTextMatcher.java:83: error: cannot find symbol
    [javac]     Counter<String> stemFeatures = new ClassicCounter<String>();
    [javac]     ^
    [javac]   symbol:   class Counter
    [javac]   location: class TextToTextMatcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/TextToTextMatcher.java:83: error: cannot find symbol
    [javac]     Counter<String> stemFeatures = new ClassicCounter<String>();
    [javac]                                        ^
    [javac]   symbol:   class ClassicCounter
    [javac]   location: class TextToTextMatcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/TextToTextMatcher.java:90: error: cannot find symbol
    [javac]       Counters.maxInPlace(tokenFeatures, TokenLevelMatchFeatures.extractTokenMatchFeatures(exampleTokens, fbDescTokens, true));
    [javac]       ^
    [javac]   symbol:   variable Counters
    [javac]   location: class TextToTextMatcher
    [javac] /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/TextToTextMatcher.java:91: error: cannot find symbol
    [javac]       Counters.maxInPlace(tokenFeatures, TokenLevelMatchFeatures.extractTokenMatchFeatures(exampleLemmas, fbDescTokens, true));
    [javac]       ^
    [javac]   symbol:   variable Counters
    [javac]   location: class TextToTextMatcher
    [javac] Note: /home/ritik/rashi/src/edu/stanford/nlp/sempre/freebase/LambdaCalculusConverter.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 100 errors

BUILD FAILED
/home/ritik/rashi/build.xml:65: Compile failed; see the compiler error output for details.

Total time: 2 seconds

**Comment by ppasupat** [comment]
This looks like the dependendies for freebase was not loaded. Could you try running the following:
```
ant clean
./pull-dependencies core corenlp freebase
ant freebase
```

**Comment by mr-asleep** [comment]
Okay. Thanks
