### ISSUE TITLE
Empty list returned on querying freebase

### ISSUE THREAD

**Issue by mr-asleep** [percyliang/sempre#202]
Hello,

When I try to run this command:
./run @mode=simple-freebase-nocache @sparqlserver=localhost:3001
and write (execute fb:en.california) in the prompt, I am getting an empty list.
Output- 
SparqlExecutor.execute: fb:en.california 
  (list)
I have pulled all the dependencies. Please help me solve the issue. Thanks!

**Comment by ppasupat** [comment]
Sorry, I'm unable to run virtuoso on my machine right now. But could you try adding the following to the command line to dump debug information:
```
--SparqlExecutor.verbose 10
```

**Comment by ppasupat** [comment]
Make sure you ran the `add` command in the [Setting up your own Virtuoso graph database](https://github.com/percyliang/sempre/blob/master/TUTORIAL.md#setting-up-your-own-virtuoso-graph-database) section. The command is
```
freebase/scripts/virtuoso add freebase/data/tutorial.ttl 3001
```
Otherwise the database will be empty.

**Comment by mr-asleep** [comment]
> Make sure you ran the `add` command in the [Setting up your own Virtuoso graph database](https://github.com/percyliang/sempre/blob/master/TUTORIAL.md#setting-up-your-own-virtuoso-graph-database) section. The command is
> 
> ```
> freebase/scripts/virtuoso add freebase/data/tutorial.ttl 3001
> ```
> 
> Otherwise the database will be empty.

This is what happens when I type the add command:

freebase/scripts/virtuoso add freebase/data/tutorial.ttl 3001

/home/ritik/sempre/fig/lib/myutils.rb:276:in `block in extractArgs': Unknown type: 'Fixnum' (RuntimeError)
	from /home/ritik/sempre/fig/lib/myutils.rb:261:in `each_index'
	from /home/ritik/sempre/fig/lib/myutils.rb:261:in `extractArgs'
	from fig/bin/chunk:7:in `<main>'
freebase/scripts/virtuoso:18:in `Integer': invalid value for Integer(): "" (ArgumentError)
	from freebase/scripts/virtuoso:18:in `parseInt'
	from freebase/scripts/virtuoso:130:in `add'
	from freebase/scripts/virtuoso:222:in `<main>'
Please help. Thanks

**Comment by ppasupat** [comment]
Could you try installing an older version of Virtuoso? Version 7.2.5.1 seems to work fine on my end.

1. Remove the existing `virtuoso-opensource` directory.
1. Download [Virtuoso Open Source Edition v7.2.5.1](https://github.com/openlink/virtuoso-opensource/releases). Extract the **source zip** as `virtuoso-opensource`.
1. Follow the installation instruction from [README](https://github.com/percyliang/sempre/blob/master/README.md#virtuoso-graph-database), and then [set up the database](https://github.com/percyliang/sempre/blob/master/TUTORIAL.md#setting-up-your-own-virtuoso-graph-database)
