### ISSUE TITLE
How to get sparql expressions stored in a file?

### ISSUE THREAD

**Issue by mr-asleep** [percyliang/sempre#206]
Hi,
I am getting the sparql expressions in the log file. But is there any way to get them in a text file in an organised manner.

This is the command that I am using:
./run @mode=simple-freebase-nocache @sparqlserver=localhost:3001 -Grammar.inPaths dbpedia/dbpedia.grammar -SimpleLexicon.inPaths dbpedia/output.lexicon -SparqlExecutor.verbose 10  -FeatureExtractor.featureDomains rule opCount constant whType lemmaAndBinaries denotation lexAlign joinPos skipPos -Dataset.inPaths test:dbpedia/que.json -Learner.maxTrainIters 0 -exec.execDir dbpedia/out/
Please help me to get the sparql expression for each top predicted candidate in an output file just like how we get top predicted derivation for each utterance

**Comment by ppasupat** [comment]
Unfortunately, the SPARQL queries only exist in the [internal computation of `SparqlExecutor`](https://github.com/percyliang/sempre/blob/7b9f4625c661cbffa08ecbf8e684651a247b4367/src/edu/stanford/nlp/sempre/freebase/SparqlExecutor.java#L164). The query seems to be discarded after execution.

Currently, the possible options would be:
- Dump the SPARQL queries to a file inside `SparqlExecutor`. This option would print the queries in an arbitrary order.
- Reconvert each `Formula` to a SPARQL query (call the [first part of the `execute` method](https://github.com/percyliang/sempre/blob/7b9f4625c661cbffa08ecbf8e684651a247b4367/src/edu/stanford/nlp/sempre/freebase/SparqlExecutor.java#L242-L248)).

**Comment by mr-asleep** [comment]
Okay. Thanks a lot
