### ISSUE TITLE
Prefix "fb:"

### ISSUE THREAD

**Issue by stbusch** [percyliang/sempre#215]
Hello,
the tutorial says 

> fb:en.california is the canonical Freebase ID (always beginning with the prefix fb:)

Do I understand correctly that this prefix is part of the SPARQL syntax referring to Freebase (and not part of the Freebase syntax itself)?

thanks

**Comment by ppasupat** [comment]
Prefixing with ":" is part of the SPARQL syntax in standard SPARQL, but in SEMPRE, the prefix "fb:" is only a naming scheme and is not tied to the syntax.

The prefix "fb:" is originally used to denote entities and relations in Freebase. But after a while, we started using "fb:" to denote any arbitrary entities and relations, even ones outside Freebase.

**Comment by stbusch** [comment]
I see, thanks.
