### ISSUE TITLE
What are the commands to evaluate predictions on the overnight dataset?

### ISSUE THREAD

**Issue by subendhu19** [percyliang/sempre#227]
I have a text file of predicted canonical forms from which I want to compute the denotation accuracy. The canonical forms in this file are predicted by a simplification model that simplifies general utterances into a fixed canonical form so that they can then be parsed by the grammar rules. So now, I need to run the fixed grammar rules to parse the predicted canonical utterances and then execute the logical forms to get the denotation accuracy. What commands should I run for this?

**Comment by ppasupat** [comment]
Duplicate of #222.
