### ISSUE TITLE
SEMPRE for Chinese sentence analysis

### ISSUE THREAD

**Issue by laotao** [percyliang/sempre#27]
I'm struggling to use this for Chinese sentence analysis. Processes up to parser is ok now. But I'm stuck at the LexiconFn process.

The LexiconFn looks up entities in the "lib/lucene/4.4" indexes, which, I guess, was produced by the fbalignment.index.FbEntityIndexer class. A "datadump file" is mentioned in the class but I cannot find it in the project repository. 

Can I have a look at what the "datadump file" look like? Maybe I can create a Chinese version of that file and index it.

Thanks

**Comment by killa1218** [comment]
哥们加油啊

**Comment by yfliao** [comment]
Dear Laotao,

I seems that you had implemented a Chinese version of San Francisco semipro parser. Could you show us how to do it? For example, which files should we modify and how?

Thanks a lot!

**Comment by laotao** [comment]
@yfliao Yes I worked out the '圣弗朗西斯科' case. But that's all. I cannot go any further as simple as a Chinese version of 'Physicists of San Francisco' and I've abandoned the plan. There are too many work to do to use the full power of Sempre for Chinese. Every step in the Chinese parser pipeline need improvement. I cannot do them all.

**Comment by yfliao** [comment]
Dear Laotao,

Thanks for your quick reply.

Could I have your codes as a good starting point? So far, I have no idea where to find the right files/items, especially, where to put the Chinese lemma tokens and lexicon?

And do you know how to write a grammar that could parse ill-form sentences? For example, “what mhmm is mhmm three plus four?” or “wwhat iis three plus four?”or even “what xxx is yyy three xxx plus www four vvv?”.

Have a nice weekend!

Best Regards,
yuanfu

**Comment by laotao** [comment]
I didn't use github in the first place. But in case the work may be useful someday I copied some of the files that appeared in the svn history to here now. It may block building for the moment because the changes were made last year on an old version of Sempre. 

The code files I changed mainly include the followings:
https://github.com/laotao/sempre/blob/master/src/edu/stanford/nlp/sempre/LanguageInfo.java
https://github.com/laotao/sempre/blob/master/src/edu/stanford/nlp/sempre/Example.java
https://github.com/laotao/sempre/blob/master/src/edu/stanford/nlp/sempre/Master.java
https://github.com/laotao/sempre/blob/master/src/edu/stanford/nlp/sempre/fbalignment/lexicons/UnaryLexicon.java
https://github.com/laotao/sempre/blob/master/Makefile

It is also needed to replace the English Stanford parser lib to the Chinese version.

I've also made some change to the data files to make '圣弗朗西斯科' work, including:
https://github.com/laotao/sempre/blob/master/data/tutorial.ttl
lib/fb_data/6/unaryInfoStringAndAlignment.txt.bz2 
lib/fb_data/93.exec/schema.ttl.bz2
lib/libjcsi.jar

The last thing to do is to produce entities in the "lib/lucene/4.4" indexes using the fbalignment.index.FbEntityIndexer class, as discussed in this issue.
