### ISSUE TITLE
Ubuntu 14.04

### ISSUE THREAD

**Issue by cerisara** [percyliang/sempre#28]
The Quickstart.md says to checkout the v7.0.0 tag for virtuoso, but this version of virtuoso does not compile under Ubuntu 14.04, because of an upgrade of bison that is not compatible any more with virtuoso v7.0.0.
However, it looks like you can rather checkout the 042f142 commit, which has a patch to fix this problem with Ubuntu 14.04. I've just tried, and it looks like it's working fine with sempre...

**Comment by JasonSmLing** [comment]
Can you please tell me,simply
It means,What change I have to do in this?

 # For Ubuntu, make sure these dependencies are installed
    sudo apt-get install -y automake gawk gperf libtool bison flex libssl-dev
    # Clone into sempre folder
    git clone https://github.com/openlink/virtuoso-opensource
    cd virtuoso-opensource
    git checkout tags/v7.0.0
    ./autogen.sh
    ./configure --prefix=$PWD/install
    make
    make install
    cd ..

**Comment by cerisara** [comment]
Sorry for the delay,

you just change the line
"git checkout tags/v7.0.0"
with
"git checkout 042f142"
and it should work...

**Comment by JasonSmLing** [comment]
Tnks alot Mr cerisara.have a good times.
