### ISSUE TITLE
indicator features

### ISSUE THREAD

**Issue by amirSharif32dm** [percyliang/sempre#31]
Hello

Would you please told me,what does "indicator features" means in this part?
{Each derivation d is the result of applying some number of intersection, join, and bridging operations. To control this number, we define indicator features on each of these counts. }

Tnx

**Comment by lxafly** [comment]
Hello:

I am using SEMPRE and I happen to read the code. In FeatureVector.java they defined indicator features
Basically:
 Indicator features: the feature value is either 0(not present); 1(present) 
 General features: the feature value is a REAL value.
