### ISSUE TITLE
Problem in virtuoso

### ISSUE THREAD

**Issue by JasonSmLing** [percyliang/sempre#33]
Hello
I have moved from step to step of QUICKSTART
but in  "Install the Database"
for comment "make"
This error is appeared: Can u please told me how can I pass it?

make: *** No targets specified and no makefile found.  Stop.

**Comment by amirSharif32dm** [comment]
Hi 

I had same problem...
Check this links:
http://askubuntu.com/questions/103348/error-when-installing-makefile-make-no-targets-specified-and-no-makefile
http://askubuntu.com/questions/579418/problem-in-installing-virtuoso-make
https://github.com/openlink/virtuoso-opensource/issues/160
https://github.com/percyliang/sempre/issues/28

good luck

**Comment by JasonSmLing** [comment]
Thank you Mr amirSharif32dm.It was  effective.
