### ISSUE TITLE
Problem in Evaluation

### ISSUE THREAD

**Issue by lkq1992yeah** [percyliang/sempre#34]
Hi, I encountered a problem in evaluation step.
Suppose the test parsing example is (example (utterance "what is the capital of france?") (targetValues (description "Paris"))), I output its target value, which is "(description Paris)". However, for the top derivation of this example, the target value is "(list (name fb:en.paris Paris))". The answer is correct, but when evaluated, it's judged as negative answer, because these two target values are not the same in string level, the compatibility score is 0 (computed at Parser.java, line 246).
I think that I made a mistake somewhere, is there anyone who encountered this problem before, and tell me how to do? Thanks in advance.

**Comment by lkq1992yeah** [comment]
Err.. Well, I solved the problem. The target value is represented in DescriptionValue, while the output value is represented in ListValue, which makes compatibility=0. I should write "(list (description Paris))" in my testinput file. (I was misleaded by the samples in QUICKSTART.md, maybe the author can edit it, in order to avoid this problem)

**Comment by lindabai** [comment]
Hi, we tried to test the sempre 1.0 as the tutorial told and we also met the same problem. In the original QUICKSTART file, the testinput includes **(example (utterance "what is the capital of france") (targetValues (description "Paris")))**. But actually the correct format should be** (example (utterance "what is the capital of france") (targetValues (list (description Paris))))  ** The mistake still exists and confuses the others and we suggest to modify the QUICKSTART file asap
