### ISSUE TITLE
Question SEMPRE vs SPF

### ISSUE THREAD

**Issue by silentrob** [percyliang/sempre#36]
Can anyone explain the differences semantic or high level goals between SEMPRE and SPF[1]

They both seem to use a CCG and Lambda calculus to convert natural language to a logical form. 
I know SPF has a ML layer for getting to the solution while hiding some of the parsing internals. 

Perhaps they projects target sets of use-cases and I simply overlooked it.

[1] https://bitbucket.org/yoavartzi/spf

**Comment by yonatansito** [comment]
At a very high-level both are semantic parsers that are developed by
different research groups, so there is some substantial overlap.
I don't know how to exactly compare the two, I guess we focus on training
parsers from denotations rather than logical forms, but I recommend going
through our tutorial to get a better sense of what's available.

**Comment by percyliang** [comment]
Things on which SPF is better than SEMPRE:
- Better support for inducing lexical entries (e.g., GENLEX).
- Better support for lambda calculus and CCG.

SEMPRE has the following that SPF lacks:
- You can use different linguistic formalisms (you can use CCG, a more conventional S -> NP VP grammar, or custom rules).
- You can use different logical forms (you can use lambda DCS or Java programs).
- There is more support for execution of logical forms (e.g., Virtuoso or Java).
- There is a power "grammar" file (really, a configuration file), which allows you to configure your experimental setup.
- There is a interactive repl and a web interface which allows you to play around with the semantic parser, change the model on the fly, call Java, etc. (see the TUTORIAL).
- More documentation.

There are also other differences ranging from software engineering decisions to semantic parsing modeling decisions, which are probably too technical to go into.

Finally, SEMPRE is under active development and is the foundation of several semantic parsing projects at Stanford, so expect it to improve and become more featureful over the next few years.

**Comment by silentrob** [comment]
Great answer - thank you! 
Big plus one for the Documentation, Tutorial and REPL.

**Comment by evbo** [comment]
@percyliang any thoughts you can share on comparison of sempre vs [ccg2lambda](https://github.com/mynlp/ccg2lambda)?
