### ISSUE TITLE
Permission error when downloading dependencies

### ISSUE THREAD

**Issue by cegme** [percyliang/sempre#38]
Hello, I am getting a 403 error when obtaining the Freebase type file.

This issue occurs when running `./pull-dependencies fullfreebase-types`

I can download the rest of the files. The file with the permission problem is located here:
http://nlp.stanford.edu/software/sempre/dependencies-2.0/u/nlp/data/semparse/scr/freebase/freebase-rdf-2013-06-09-00-00.canonicalized.en-types.gz

**Comment by percyliang** [comment]
Should be fixed now.

**Comment by cegme** [comment]
It is fixed. Thanks!

**Comment by lxafly** [comment]
Hello:

This link cannot be accessed now: 
http://nlp.stanford.edu/software/sempre/dependencies-2.0/u/nlp/data/semparse/scr/freebase/freebase-rdf-2013-06-09-00-00.canonicalized.en-types.gz
Do you know the link where this data is currently stored?
Thanks!

**Comment by ppasupat** [comment]
The link should be restored now.

**Comment by lxafly** [comment]
It is, thanks a lot!

**Comment by JilongZhang** [comment]
Hello：
       I want to ask some questions about CRF ，can you tell me your email

**Comment by JilongZhang** [comment]
my email is 64732913@qq.com
