### ISSUE TITLE
sempre papers

### ISSUE THREAD

**Issue by chengiant** [percyliang/sempre#39]
Hi Liang,
I do read the suggested papers, and was in a chaos:
The paper "Bringing machine learning and compositional semantics together" says: "We use [u] for
the translation of syntactic expression u into its semantic representation".

So ,Does Sempre realize the translation from syntactic tree to semantic tree? 
This is very important to me, thanks.

**Comment by percyliang** [comment]
SEMPRE parses directly from the words, but you can define features on the
dependency tree of the words to guide the parsing.
