### ISSUE TITLE
Freebase moving forward

### ISSUE THREAD

**Issue by silentrob** [percyliang/sempre#40]
With Freebase shutting down, is the plan to work with WikiData? Or something else?

Perhaps just a more generic way to import your own Lexicon?

**Comment by percyliang** [comment]
There are several answers.
- For the WebQuestions dataset, we will still use the 2013 Freebase
snapshot, since that's when the answers are from.
- For general question answering, WikiData is the natural thing.
- You can use whatever database you want.  SEMPRE just offers a framework.
