### ISSUE TITLE
generated formulas are too large 

### ISSUE THREAD

**Issue by uwittygit** [percyliang/sempre#42]
HI Liang,
I used Sempre1.0 Paraphrase for test.
Do you have any strategy to reduce the size of generated formulas, It seems that it produced all possible formulas for a given entity. 
like "what currency does China use ?" , there are 6000 possible formulas and 12000 possible canonical questions, which were too large.
I noticed that you used "lib/lucene/4.4/inexact" to align entities, but there were no alignment for unary or binary rules in FormulaRetriever.java. How can I generate formula with these rules to scale down the size.

**Comment by yonatansito** [comment]
Hi,
It is true that we generate basically everything that is type compatible.
You can decide to be more conservative and reduce the number of entities
per span (there is an option for that in the sempre script), or you can
decide to try and match somehow binaries and unaries to the utterance (but
we don't do that).
