### ISSUE TITLE
What is  the format to generate Lucene  File?

### ISSUE THREAD

**Issue by uwittygit** [percyliang/sempre#43]
Hi Liang,
Can you supply me the files to generate lucene files(lucene/4.4/free917)
My email: uwittygit@hotmail.com
Thanks a lot

**Comment by yonatansito** [comment]
Here is an exampe line
It is a tab-separated file with
a) the string MID
b) Freebase name
c) alignment score (computed elsewhere)
d) String description
e) Freebase types for the entity

MID fb:en.barack_obama 12493.0 Barack Obama
fb:fictional_universe.person_in_fiction,fb:people.person,fb:user.colin.default_domain.twitter_topic,fb:symbols.name_source,fb:government.political_appointer,fb:tv.tv_program_guest,fb:user.narphorium.people.nndb_person,fb:architecture.building_occupant,fb:user.narphorium.people.topic,fb:organization.organization_member,fb:influence.influence_node,fb:government.politician,fb:event.public_speaker,fb:government.us_president,fb:visual_art.art_subject,fb:film.film_story_contributor,fb:user.robert.x2008_presidential_election.topic,fb:award.award_winner,fb:base.saturdaynightlive.person_impersonated_on_snl,fb:user.loveyou2madly.default_domain.famous_author,fb:book.author,fb:people.measured_person,fb:people.appointer,fb:user.robert.default_domain.my_favorite_things,fb:biology.animal_owner,fb:book.poem_character,fb:music.artist,fb:user.jamie.sunlight.legislator,fb:user.robert.x2008_presidential_election.candidate,fb:user.robert.default_domain.presidential_candidate,fb:celebrities.celebrity,fb:organization.organization_founder,fb:base.saturdaynightlive.topic,fb:award.award_nominee,fb:m.04325tb,fb:government.polled_entity,fb:user.robert.us_congress.topic,fb:business.employer,fb:book.book_subject,fb:film.film_subject,fb:film.person_or_entity_appearing_in_film,fb:government.u_s_congressperson,fb:common.topic,fb:award.ranked_item,fb:internet.social_network_user,fb:media_common.quotation_subject,fb:broadcast.producer,fb:user.neothilic.default_domain.funny_guy

**Comment by uwittygit** [comment]
Thanks
