### ISSUE TITLE
Questions on alignment

### ISSUE THREAD

**Issue by uwittygit** [percyliang/sempre#44]
Hi,
what alignment tool did you use? giza++?  fast_align?
and I noticed that, in /lib/paralex/phrase-table.counts.txt, the align format is:
         phrase1    phrase2    cooccurrenceCount     phrase1Count     phrase2Count
It is quite weird that cooccurrenceCount could be larger than phrase1Count or phrase2Count, Why?
e.g
         unix and linux ?	    linux and unix ?	    52.0	    9.0	   7.0
         in zucchini	           in zuccinus	            14.0	    11.0	   4.0

**Comment by uwittygit** [comment]
HI,
I used standard moses training method to generate phrase table.
use france-english corpus
phrase-table format:
améliorer les ||| improvements in the ||| 0.166667 0.00925752 0.0192308 6.73783e-05 ||| 0-0 1-2 ||| 6 52 1 ||| |||

in this example, does  6 52 1 corespond to " cooccurrenceCount , phrase1Count , phrase2Count" in Sempre ?

**Comment by yonatansito** [comment]
We use our own alignment algorithm. See our paper for EMNLP 2013 for
details.

**Comment by uwittygit** [comment]
HI  yonatansito,
Thanks for your reply.
        I used Sempre1.0 paraphrase algorithm for test, So I read your paper "acl 2014" for reference.
The alignment question I am talking about is the alignment for questions with the same meanings, not the alignment for binary unary or entity to freebase.
        The correspond data sempre supplied is in "lib/paralex/phrase-table.counts.txt".

        And in the paper "Semantic Parsing via Paraphrasing", It said: "Paraphrase pairs in PARALEX are word-aligned using standard machine translation methods. We use the word alignments to construct a phrase table by applying the consistent phrase pair heuristic (Och and Ney, 2004) to all 5-grams"
       So I used moses in order to reproduce my own phrase-table. But I am confused in the data format moses generated (see the question above).
       Or can you tell me, what is the "standard translation methods" you appied?
      Thanks.

**Comment by yonatansito** [comment]
Oh, ok.
The word alignment was taken from Anthony Fader's paper and resource
http://knowitall.cs.washington.edu/paralex/

The phrase alignment was done using the word alignment using Och and Ney
2004.
We keep any phrase pair that was aligned at least K time, I think K=10.
About the numbers - basically we eventually ignored them so you can ignore
them too. I don't know enough about moses output to tell you what those are
exactly.
