### ISSUE TITLE
my problem in Sempre 1.0

### ISSUE THREAD

**Issue by SaraMitchell** [percyliang/sempre#49]
Hello all

I am really confused in something
When I run this command that is said in *Quickstart.md*:
>     ./sempre @mode=train \
             @domain=webquestions \
             @sparqlserver=localhost:3093 \
             @cacheserver=local \
             -Learner.maxTrainIters 0 \
             -Dataset.inPaths test:testinput \
             -Builder.inParamsPath lib/models/15.exec/params \
             -Grammar.inPaths lib/models/15.exec/grammar \
             -Dataset.readLispTreeFormat true

sometime *SparqlExecutor.execute* output comes in my log and sometimes it dosent come!!!!!!!
> SparqlExecutor.execute: (fb:user.moritzstefaner.maceproject.lesson.interactivity_level fb:m.0sn7v5c) 
              SparqlExecutor.execute: (fb:user.dsp13.default_domain.user_group.interesting_topics fb:en.three_plus) 
              SparqlExecutor.execute: (fb:user.dsp13.default_domain.user_group.interesting_topics fb:m.0sn7v5c) 
              SparqlExecutor.execute: (fb:user.avic.assertion_modeling_kit.freebase_proposition.input_2 fb:m.0smftlj) 
              SparqlExecutor.execute: (fb:user.moritzstefaner.maceproject.lesson.interactivity_level fb:m.0smftlj) 
              SparqlExecutor.execute: (fb:user.avic.assertion_modeling_kit.freebase_proposition.input_2 fb:en.three_plus) 
              SparqlExecutor.execute:
 

I always use same command!

**Comment by SaraMitchell** [comment]
and My virtusea is running in 3093:

> Sara@ubuntu:~$ sudo netstat -taupen
[sudo] password for Sara: 
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 0.0.0.0:3093            0.0.0.0:*               LISTEN      1000       43468       11694/virtuoso-t
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      0          15594       1837/dnsmasq    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      0          28482       4719/cupsd      
tcp        0      0 0.0.0.0:13093           0.0.0.0:*               LISTEN      1000       43464       11694/virtuoso-t
tcp        0      0 127.0.0.1:43434         0.0.0.0:*               LISTEN      0          16517       2145/kvpncsvc   
tcp        0      0 127.0.0.1:35914         127.0.0.1:13093         ESTABLISHED 1000       43466       11694/virtuoso-t
tcp        0      0 127.0.0.1:13093         127.0.0.1:35914         ESTABLISHED 1000       35227       11694/virtuoso-t

**Comment by yonatansito** [comment]
We have cache file whenever the query is not in the cache file you
will see SparqlExecutor.execute,
if it is in the cache file you won't.

**Comment by SaraMitchell** [comment]
Oh That is really fantastic
It is really cleverly
Thank you yonatansito
