### ISSUE TITLE
EMNLP 2013 model

### ISSUE THREAD

**Issue by amirSharif32dm** [percyliang/sempre#51]
Hi 

I have read your paper over 50 times,but I dont understand a part....
this picture shows what I m understanding about 'Train phase' of model
Do you please tell me,what is my mistake??
please please please

![pic01-01](https://cloud.githubusercontent.com/assets/9320069/7795021/583b5d60-02c0-11e5-93e2-c1f2ea0f7ebe.jpg)

if it is like above,but what does "alignment"  means in ACL2014?
> We also generate canonical utterances using
an alignment lexicon, released by Berant et al.
(2013), which maps text phrases to Freebase binary predicates

it takes the mind to there is "a lexicon which is made offline" that maps phrases to fb predicates.

**Comment by yonatansito** [comment]
Hmmm the diagram is not perfect (as far as I understand it) for example, to
create the derivation d_1, d_2, ... you need the example x_1 (and for
extracting features also y_1). Also I don't really understand the semantic
of arrows and their colors.

As for the second question - yes, we have an offline step that aligns
phrases to predicates. The lexicon is the output of what's described in the
Alignment part of Emnlp 2013, and it is used to build derivations (d_1,
d_2, ...) and extract features as well.

In Acl 2014 we use this lexicon in a non-tradiational way for generation.
When we see a logical form with a binary predicate b, we generate a phrase
from it by looking at the phrase that has the "best" alignment to b, where
best is defined by some metric.

Hope this helps.

**Comment by amirSharif32dm** [comment]
so Thanks Mr yonatansito.
my english is not good,I tried to ask like this.......but I should have drawn better diagram :(
