### ISSUE TITLE
Problems with Freebase Querying

### ISSUE THREAD

**Issue by atechnicolorskye** [percyliang/sempre#53]
Hi Percy,

I'm having issues with the run modes query and simple freebase.

For the command ./run @mode=query @sparqlserver=localhost:3001 -formula '(fb:location.location.containedby fb:en.california)' in the tutorial, I get:
Error: Could not find or load main class edu.stanford.nlp.sempre.freebase.SparqlExecutor
Command failed: java -ea -cp libsempre/*:lib/* edu.stanford.nlp.sempre.freebase.SparqlExecutor -SparqlExecutor.endpointUrl http://localhost:3001/sparql -formula (fb:location.location.containedby fb:en.california)

Anf for ./run @mode=simple-freebase @sparqlserver=localhost:3001, having started the Virtuoso database, I get:
/usr/local/bin/rlwrap
Problem processing: freebase edu.stanford.nlp.sempre.freebase.BinaryLexicon
Exception in thread "main" java.lang.RuntimeException: java.lang.ClassNotFoundException: edu.stanford.nlp.sempre.freebase.BinaryLexicon
	at edu.stanford.nlp.sempre.Master.getOptionsParser(Master.java:434)
	at edu.stanford.nlp.sempre.Main.main(Main.java:38)
Caused by: java.lang.ClassNotFoundException: edu.stanford.nlp.sempre.freebase.BinaryLexicon
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at edu.stanford.nlp.sempre.Master.getOptionsParser(Master.java:428)
	... 1 more
Command failed: rlwrap java -Dmodules=core,freebase -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -executor freebase.SparqlExecutor -SparqlExecutor.endpointUrl http://localhost:3001/sparql -FreebaseSearch.cachePath FreebaseSearch.cache -EntityLexicon.mid2idPath freebase.cloudapp.net:4000:freebase-rdf-2013-06-09-00-00.canonical-id-map.gz -TypeInference.typeLookup freebase.FreebaseTypeLookup -FreebaseTypeLookup.entityTypesPath freebase.cloudapp.net:4000:freebase-rdf-2013-06-09-00-00.canonicalized.en-types.gz -EntityLexicon.maxEntries 2 -FeatureExtractor.featureDomains rule -Parser.coarsePrune -JoinFn.typeInference -UnaryLexicon.unaryLexiconFilePath /dev/null -BinaryLexicon.binaryLexiconFilesPath /dev/null -Grammar.inPaths freebase/data/demo1.grammar -SparqlExecutor.returnTable -Main.interactive

Thanks for all the help :)

Cheers,
Sky

**Comment by percyliang** [comment]
You need to do
./pull-dependencies freebase
make freebase

**Comment by atechnicolorskye** [comment]
Hi Percy,

Thanks for the quick reply.

That was I was missing. I assume I should run make for all dependencies pulled then.

Cheers,
Sky

**Comment by osmode** [comment]
Hello Percy,

I'm getting the same error messages as Sky, which are persisting even after I run the following two commands:
./pull-dependencies freebase        and 
make freebase

Just to clarify, do I need to install the full freebase to run the queries in the tutorial? I didn't actually download the entire 60GB file on my machine (Ubuntu 14.04). 

Thanks for your help.
Omar

**Comment by aman313** [comment]
Hi @percyliang ,

I am facing the same issue as above.

@osmode  Kindly let me know if you found a workaround.

Cheers,
Aman

**Comment by sushilks** [comment]
"make freebase" did not work for me as there is no Makefile.
instead use "ant freebase"

**Comment by zhenduow** [comment]
> "make freebase" did not work for me as there is no Makefile.
> instead use "ant freebase"

Thank you very much! It solves my problem.
