### ISSUE TITLE
string "null" problem - resulting from ConcatFn

### ISSUE THREAD

**Issue by lxafly** [percyliang/sempre#60]
Hello! 

I'm using the SEMPRE 2.0 to build a semantic parser, and I just started with a toy grammar. But I'm confused about the behavior of the parser, could you provide some hints?
So here the grammar:
------------------------------------------------------------------(case1)
    (rule $Word ($TOKEN) (IdentityFn))
    (rule $ShopName ($Word)  (lambda x (call + (string ShopName:) (var x))))
    (rule $ShopName ($ShopName $Word) (ConcatFn " :"))
    (rule $ROOT ($ShopName) (IdentityFn))

The input sentence: "sushi bar"
What I expect is:     ShopName :sushi :bar
What I got is:           null:bar
-------------------------------------------------------------------(case2)
So if the grammar is as follows:
    (rule $Word ($TOKEN) (IdentityFn))
    (rule $ShopName ($Word)  (IdentityFn))
    (rule $ShopName ($ShopName $Word) (ConcatFn " :"))
    (rule $ROOT ($ShopName) (IdentityFn))
And with the input sentence "sushi bar"
I got "sushi bar". (Correct)
-------------------------------------------------------------------(case3)
Also, if the grammar is as follows:
    (rule $Word ($TOKEN) (IdentityFn))
    (rule $ShopName ($Word)  (lambda x (call + (string ShopName:) (var x))))
    (rule $ROOT ($ShopName) (IdentityFn))
And the input is "bar"
I got     "ShopName:bar"   , which is correct

So is there anything wrong with the lambda part? What does it produce a null value in case1, while it is correct in case3? 
Shouldn't the executed output from the lambda function be passed on to the root node?
And this is in interactive mode ./run @mode=simple.   If there any other command that I need to specify? 

Thanks for the help!

**Comment by yonatansito** [comment]
The reason is that you are concatenating a CallFormula to a String and in
the line:

out.append(c.childStringValue(i));

the string value for the child that is the CallFormula is null.
I agree this is not the most intuitive behavior in this scenario for ConcatFn.

**Comment by lxafly** [comment]
Thank you for the quick response!
So I should avoid using CallFormula together with the ConcatFn?
What would you suggest if I wanted to concatenate two nodes, and one nodes has a value from a call function? 

Thanks for the help!

**Comment by lxafly** [comment]
So I got the following alternative to work, I used
         (lambda x (lambda y (call + (var x) (string :) (var y)))))
in place of 
         (ConcatFn ":")
But I'm still curious to know your suggestions :) Thanks!

**Comment by lxafly** [comment]
Also, is there a way to print out the detailed error message, like the path of the triggered exceptions?
What did you use to locate this specific function?
out.append(c.childStringValue(i));
Thanks!

**Comment by yonatansito** [comment]
In interactive mode, I did:
(set Parser.verbose 5)
and examined where things went wrong.
