### ISSUE TITLE
fullfreebase-vdb not found

### ISSUE THREAD

**Issue by markusdr** [percyliang/sempre#61]
I tried to pull fullfreebase-vdb, as described in the tutorial, but it gave a file not found error:

$  ./pull-dependencies fullfreebase-vdb
===== Downloading fullfreebase-vdb: Freebase (Virtuoso database)
/u/nlp/data/semparse/scr/freebase/state/execs/93.exec/vdb.tar.bz2
--2015-06-24 02:10:39--  http://nlp.stanford.edu/software/sempre/dependencies-2.0/u/nlp/data/semparse/scr/freebase/state/execs/93.exec/vdb.tar.bz2
Resolving nlp.stanford.edu... 171.64.67.140
Connecting to nlp.stanford.edu|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-06-24 02:10:40 ERROR 404: Not Found.

**Comment by markusdr** [comment]
Is there any chance that this link can be fixed? Or is there any other location where one could download that dump? 

AFAIK, it is a simplified format compare to what is (was) available directly from Google (https://developers.google.com/freebase/data).

Thanks!
Markus

**Comment by yonatansito** [comment]
I think it is fixed now (I didn't fix it, but I just tried this and it
worked):
> git clone https://github.com/percyliang/sempre.git
> ./pull-dependencies fullfreebase-vdb

**Comment by markusdr** [comment]
Yes, I was able to pull it now. Thanks!
