### ISSUE TITLE
ant core fails - cannot find symbol

### ISSUE THREAD

**Issue by tc64** [percyliang/sempre#62]
Thanks for putting your software online!
I get these errors from javac:

 [javac] Compiling 71 source files to /home/tcassidy/sempre/classes
    [javac] /home/tcassidy/sempre/src/edu/stanford/nlp/sempre/ParserAgenda.java:25: error: cannot find symbol
    [javac] class ListParserAgenda implements ParserAgenda<PrioritizedDerivationStream> {
    [javac]                                                ^
    [javac]   symbol: class PrioritizedDerivationStream
    [javac] /home/tcassidy/sempre/src/edu/stanford/nlp/sempre/ParserAgenda.java:27: error: cannot find symbol
    [javac]   private List<PrioritizedDerivationStream> agenda = new ArrayList<>();
    [javac]                ^
    [javac]   symbol:   class PrioritizedDerivationStream
    [javac]   location: class ListParserAgenda
    [javac] /home/tcassidy/sempre/src/edu/stanford/nlp/sempre/ParserAgenda.java:35: error: cannot find symbol
    [javac]   public boolean add(PrioritizedDerivationStream item, double priority) {

etc...

[javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 17 errors

**Comment by ppasupat** [comment]
Could you try running the following?

```
ant clean
./pull-dependencies core
./pull-dependencies corenlp
ant core
```

**Comment by tc64** [comment]
This worked! Thanks.
