### ISSUE TITLE
Training SEMPRE 2.0 and saving parameters -- no outputs

### ISSUE THREAD

**Issue by lxafly** [percyliang/sempre#65]
Hello!

I'm struggling with getting the correct command to train and save parameters. Using the command below,  the output file for the parameters is always empty. (output is in for example: runOutputs/params.6 )

This is the command I used:

./run @mode=simple -Grammar.inPaths data/grammar.sempre.v1.3 -FeatureExtractor.featureDomains rule -Dataset.inPaths train:data/withGaze.trueGrammar.examples -Learner.maxTrainIters 3 -interactive false  -Parser.verbose 5 -Parser.coarsePrune true -exec.execDir runOutputs/ -Learner.updateWeights true -Params.initWeightsRandomly true 

Note: I am using my own grammar and a toy training example.  It ran and parse correctly, but just did not produce the parameters (the weights). 

I guess I’m missing some necessary arguments in the command, but I could not find it in the tutorial. 
Do you know what it's missing? 

Thank you so much!

**Comment by ppasupat** [comment]
Did the program generate a file named `runOutputs/params`?

I used the following command (which uses the tutorial grammar and examples) and the params file is generated correctly:
```
./run @mode=simple -Grammar.inPaths data/tutorial-arithmetic.grammar -FeatureExtractor.featureDomains rule -Dataset.inPaths train:data/tutorial-arithmetic.examples -Learner.maxTrainIters 3 -interactive false -Parser.verbose 5 -Parser.coarsePrune true -exec.execDir runOutputs/ -Learner.updateWeights true -Params.initWeightsRandomly true
```

If the file is generated but is empty, one possible reason is that all the learned feature weights are zero. Try checking the log file (`runOutputs/log`) and see if any weight got updated.

**Comment by lxafly** [comment]
Thanks so much for sharing the command! 
I was able to solve it and indeed it was because no features were added to the weights file.
