### ISSUE TITLE
Errors in running Sempre1.0 on Free917 dataset

### ISSUE THREAD

**Issue by cdzhan** [percyliang/sempre#67]
Hi,  
       I failed in running both Sempre and Parasempre on Free917 dataset:
<---------------------------------------------------------------------------------------------------------------------->
In Parasempre,
      my command: 
           ./parasempre @mode=train  @sparqlserver=localhost:3093  @domain=free917 @cacheserver=local  @data=1
      error: ( I have changed the parameter "-Xmx10g" to "-Xmx25g" in parasempre.rb, but no help )
          ERROR: java.lang.RuntimeException: java.lang.OutOfMemoryError: GC overhead limit exceeded:
fig.basic.Parallelizer.process(Unknown Source)
edu.stanford.nlp.sempre.paraphrase.ParaphraseLearner.processParsingExamples(ParaphraseLearner.java:114)
edu.stanford.nlp.sempre.paraphrase.ParaphraseLearner.learn(ParaphraseLearner.java:74)
edu.stanford.nlp.sempre.paraphrase.ParaphraseLearner.learn(ParaphraseLearner.java:55)
edu.stanford.nlp.sempre.paraphrase.ParaphraseMain.run(ParaphraseMain.java:36)
fig.exec.Execution.runWithObjArray(Unknown Source)
fig.exec.Execution.run(Unknown Source)
edu.stanford.nlp.sempre.paraphrase.ParaphraseMain.main(ParaphraseMain.java:90)
            ERROR: Caused by java.lang.OutOfMemoryError: GC overhead limit exceeded:
<---------------------------------------------------------------------------------------------------------------------->
In Sempre,
      my command: 
           ./sempre @mode=train @sparqlserver=localhost:3093  @domain=free917 @cacheserver=local @data=1
      error: ( occured in the 2nd trainning iteration )
              BeamParser.pruneCell [$BaseSet 1:10[position does colby armstrong play on the toronto maple]]: 932871 entries
              BeamParser.pruneCell [$BaseSet 0:10[what position does colby armstrong play on the toronto maple]]: 1041159 entries
              ERROR: XML: <sparql xmlns="http:
              ERROR: XML: <sparql xmlns="http:
              ERROR: XML: <sparql xmlns="http:

Thanks in advance!

**Comment by yonatansito** [comment]
Hi,
As for the first, indeed it seems like a memory issue, so I don't have any
suggestion except for increasing memory more.
As for the second - it seems that there is some corruption in the cache
file.
you can try
@cacheserver=none
instead of
@cacheserver=local
to see if this is the problem.
If it is, make sure that you are not writing to a local cache with more
than one process at once.

**Comment by cdzhan** [comment]
Thank you! I will have a try. Now I have another question, I'm reading Berant.et.al. 2013 paper. The paper said they perform 3 random 80%-20% splits of the training set for development. I'm puzzled by the meaning of 3 random?

**Comment by yonatansito** [comment]
This means that we randomly shuffle the dataset 3 times and the do a 80/20
split. Randomness is based on the seed for the random number generator.

**Comment by cdzhan** [comment]
But I found every time I run the system, the questions in the development dataset is the same, only the order of questions changed.

**Comment by yonatansito** [comment]
To change the split you need to give a different seed by using the option
-Dataset.splitRandom <number>
The default is 1, and we used 1/2/3 to get the three random splits (not
sure why the order changes at all for you).

**Comment by cdzhan** [comment]
Hi, the order of questions was really changed. Not only in my log file I can see, but in the code I can find the corresponding commands. As in below:
<----------------------------------------------------------------------------------------------------------->
for sempre, in Dataset.java:
      int[] perm = SampleUtils.samplePermutation(opts.splitRandom, origTrainExamples.size());
      ...
      for (int i = 0; i < split1; i++)
        trainExamples.add(origTrainExamples.get(perm[i]));
      for (int i = split2; i < origTrainExamples.size(); i++)
        devExamples.add(origTrainExamples.get(perm[i]));
<------------------------------------------------------------------------------------------>
for parasempre, in DatasetUtils.java:
    int[] perm = SampleUtils.samplePermutation(rand, originalExamples.size());
    ...
    for (int i = 0; i < split1; i++)
      trainExamples.add(originalExamples.get(perm[i]));
    for (int i = split2; i < originalExamples.size(); i++)
      devExamples.add(originalExamples.get(perm[i]));

I think we should care about the order of questions, because as we know the order will also determin the training result.
 Thanks in advance! :- )

**Comment by yonatansito** [comment]
yeah and as you can see the order is determined by the opts.splitRandom
seed (for sempre).

**Comment by cdzhan** [comment]
From the log file, I found the order donot only depend on the option. For parasempre, I don't change the command: splitRandom = new Random(1), but the order still has little change. This caused my experment result not stable for the abalation exerperment, the influence of differment modules can't compare fairly for the different training order of questions. May I change the command mentioned above to get the same order? Thank you for your attention.

**Comment by yonatansito** [comment]
(1) for sempre: opts.splitRandom should control the order
(2) for parasempre: by default we use 8 threads, and then indeed the
execution is non-deterministic since the order in which things are
processed can change. You can use
-Paraphrase.learner.numOfThreads 1
to have just one thread and then the order should be fixed. But it will be
slow.

**Comment by cdzhan** [comment]
oh, I knew the reasom. Thank you very much! :-)

**Comment by yonatansito** [comment]
Just for the record its
ParaphraseLearner.numOfThreads.
