### ISSUE TITLE
Questions with Tutorial

### ISSUE THREAD

**Issue by heshizhu** [percyliang/sempre#8]
Thanks for sharing this great project.

I am having some issues when I following the tutorial. 
1. I can not find the file "data/tutorial.ttl" in any place. Is it missing?
2. What is the symbol "!" means in "(execute (argmax 1 1 (fb:type.object.type fb:location.citytown) !fb:location.location.area))". And I cannot understanding the logical forms of Superlative((argmax |rank| |count| |u| |b|)), why did you use rank and count, can you give me some more detailed explanations?

Thanks,
Shizhu

**Comment by sumeetn** [comment]
For people coming to this page for problem with starting Virtuoso Server. I was able to solve the problem, and the reason for failure for me for the location of virtuoso-opensource , it was not under sempre folder.

So by putting the  virtuoso-opensource in sempre , I was able to run the server.

**Comment by osmode** [comment]
Thank you, sumeetn, that solved it for me.
