### ISSUE TITLE
error with installing

### ISSUE THREAD

**Issue by iScienceLuvr** [percyliang/sempre#83]
After installing and even using pull-dependencies to get corenlp, I get this error when trying to run in interactive mode:

    Error: Could not find or load main class edu.stanford.nlp.sempre.Main
    Command failed: rlwrap java -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive

How can this be fixed?

**Comment by ppasupat** [comment]
Hello. Could you try rebuilding JAR files as follows?
```
ant clean
./pull-dependencies core
./pull-dependencies corenlp
ant core corenlp
```

**Comment by iScienceLuvr** [comment]
@ppasupat doesn't work. When I pull dependencies, for both of them it says "The file is already fully retrieved; there is nothing to do" and then I do the last step and there is some build error.

**Comment by ppasupat** [comment]
Could you copy and paste the build errors here?

**Comment by iScienceLuvr** [comment]
@ppasupat Here is the error:

    BUILD FAILED
/projects/72d28544-74a5-4ef0-8a93-b838af66bdc8/sempre/sempre/build.xml:34: Compile failed; see the compiler error output for details.

I have tried to reinstall it into a new folder but that still give the error. My guess is that it is looking for a class `edu.stanford.nlp.sempre.Main` when the class is actually in the src folder. It is probably not the case, but that is the only thing I can think of.

**Comment by ppasupat** [comment]
Is this the entire compiler output?
It could be the version of Java. Which version of Java are you using? The project is using Java 8.

**Comment by iScienceLuvr** [comment]
@ppasupat currently I am using Java 7 but I am trying to install Java 8 right now. Does SEMPRE 1.0 use Java 7? Does it have WebQuestions?

**Comment by ppasupat** [comment]
SEMPRE 1.0 uses Java 7 and has WebQuestions, but it is no longer supported.

**Comment by iScienceLuvr** [comment]
@ppasupat even though I upgraded from java 7 to java 8, the issue hasn't been fixed. Should I perhaps reinstall SEMPRE? is there anything else I can do?

**Comment by ppasupat** [comment]
Could you edit `build.xml` by changing all occurrences of `debug="true"` to `debug="true" verbose="true"`, rerun `ant`, and paste the output here?

**Comment by iScienceLuvr** [comment]
@ppasupat 
```
Buildfile: /projects/72d28544-74a5-4ef0-8a93-b838af66bdc8/sempre/sempre/build.xml
 
init:
     [exec] Wrote modules with 248 files to module-classes.txt: cache core corenlp freebase overnight tables
    [mkdir] Created dir: /projects/72d28544-74a5-4ef0-8a93-b838af66bdc8/sempre/sempre/classes
    [mkdir] Created dir: /projects/72d28544-74a5-4ef0-8a93-b838af66bdc8/sempre/sempre/libsempre
 
core:
     [echo] Compiling semparse: core
    [javac] Compiling 124 source files to /projects/72d28544-74a5-4ef0-8a93-b838af66bdc8/sempre/sempre/classes
    [javac] javac: invalid target release: 1.8
    [javac] Usage: javac <options> <source files>
    [javac] use -help for a list of possible options
 
BUILD FAILED
/projects/72d28544-74a5-4ef0-8a93-b838af66bdc8/sempre/sempre/build.xml:34: Compile failed; see the compiler error output for details.
```

**Comment by ppasupat** [comment]
Thank you. In this case, you need to set the `JAVA_HOME` environment variable to the installation path of Java 8. Try
```
export JAVA_HOME= ...the path to Java installation...
```
and try building again. If that works, consider adding the line above to the startup script (could be `~/.bashrc`, `~/.bashrc_profile`, or other thing depending on your operating system and shell.)

**Comment by iScienceLuvr** [comment]
@ppasupat doesn't work...

**Comment by iScienceLuvr** [comment]
@ppasupat "Error: JAVA_HOME is not defined correctly."

**Comment by ppasupat** [comment]
* What operating system are you using?
* How did you install Java 8?
* What path did you set JAVA_HOME to be?

**Comment by iScienceLuvr** [comment]
@ppasupat 

1. Ubuntu

2. Using these instructions:
http://www.tecmint.com/install-java-jdk-jre-in-linux/

Because I do not have permission to edit the the directory, I made my own opt/java directory on my local drive. 

There is one change I made. I skipped steps 5 to 9 and just added this to the terminal initialization directory:
`export PATH="~/opt/java/jdk1.8.0_45/bin/":"$PATH"`

3. I just added this line to define `JAVA_HOME`:
`export JAVA_HOME="~/opt/java/jdk1.8.0_45/bin/"`

**Comment by ppasupat** [comment]
Could you try removing `bin` at the end of the path?
On Mar 5, 2016 15:56, iScienceLuvr <notifications@github.com> wrote:@ppasupat 

UbuntuUsing these instructions:
http://www.tecmint.com/install-java-jdk-jre-in-linux/

Because I do not have permission to edit the the directory, I made my own opt/java directory on my local drive. 

There is one change I made. I skipped steps 5 to 9 and just added this to the terminal initialization directory:
export PATH="~/opt/java/jdk1.8.0_45/bin/":"$PATH"

I just added this line to define JAVA_HOME:
export JAVA_HOME="~/opt/java/jdk1.8.0_45/bin/"

**Comment by iScienceLuvr** [comment]
@ppasupat gives this: ```Error: JAVA_HOME is not defined correctly.
  We cannot execute ~/opt/java/jdk1.8.0_45//bin/java```

**Comment by ppasupat** [comment]
Hmm... I'm not sure if I know how to fix this.
* Could you try changing `~` to `$HOME`?
* Could you try executing `~/opt/java/jdk1.8.0_45/bin/java` directly on the command line?

**Comment by iScienceLuvr** [comment]
@ppasupat I tried the first one and it fixed the issue of defining JAVA_HOME except now I try to run SEMPRE and it says `Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/stanford/nlp/sempre/Main : Unsupported major.minor version 52.0` then it mentions the name of like 15 Java classes...

**Comment by iScienceLuvr** [comment]
@ppasupat here is the list of Java classes:

        at java.lang.ClassLoader.defineClass1(Native Method)

	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)

	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)

	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)

	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)

	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)

	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)

	at java.security.AccessController.doPrivileged(Native Method)

	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)

	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by ppasupat** [comment]
It could be that you compiled SEMPRE with Java 8 but run it with Java 7.

Please either use `update-alternatives` to set the default Java:

<http://askubuntu.com/questions/121654/how-to-set-default-java-version>

or set the PATH variable to include the path to Java:
```
export PATH="${HOME}/opt/java/jdk1.8.0_45/bin/:${PATH}"
```

**Comment by iScienceLuvr** [comment]
@ppasupat weird...because I have this in my terminal initialization file already: `export PATH="~/opt/java/jdk1.8.0_45/bin/":"$PATH"` 

I did install SEMPRE with java 7, then did ant clean with java 8. When I pulled the dependencies, it obviously said that the file has been already retrieved. I anyway continued and ran SEMPRE, and got this error. Maybe I should delete all the SEMpRE files and reinstall?

**Comment by iScienceLuvr** [comment]
@ppasupat I deleted my sempre folder and reinstalled it, but same error!

**Comment by ppasupat** [comment]
Could you try running `java -version` and `javac -version` to check if they are really Java 1.8?

**Comment by iScienceLuvr** [comment]
@ppasupat both are 1.8.45

**Comment by ppasupat** [comment]
Could you try running the following directly:
```
java -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive
```

**Comment by iScienceLuvr** [comment]
@ppasupat it seems to work, as it gives a list of options to continue with...

**Comment by ppasupat** [comment]
Sounds great. Now could you try this again:
```
./run @mode=simple
```
This should have the same effect as the one above. (doing `./run @mode=simple -n` with `-n` prints the command it actually executes)

**Comment by iScienceLuvr** [comment]
@ppasupat it doesn't work! I do not understand why but it shows the same error message as before with all the different Java classes...

**Comment by iScienceLuvr** [comment]
I think the issue is with the `rlwrap`... If I run `rlwrap java -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive`, it gives the same error as with `./run @mode=simple`.  However, I think I can manage to play around with logical forms using ` java -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive`.

**Comment by iScienceLuvr** [comment]
@ppasupat is there anything else I can do to fix this problem?

**Comment by ppasupat** [comment]
I'm not sure about this since it sounds like some issue beyond the scope of SEMPRE. You could put `-n` after the run command and then run the Java command it outputs.

**Comment by ppasupat** [comment]
I will be closing this issue if the code starts correctly. Please report further problems in a separate issue.

**Comment by iScienceLuvr** [comment]
@ppasupat 

> You could put -n after the run command and then run the Java command it outputs.  will be closing this issue if the code starts correctly.

But it doesn't run!! I run this: `./run @mode=simple -n`, I get this:

```
/usr/bin/rlwrap
/usr/bin/rlwrap
rlwrap java -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive
```
So I run `rlwrap java -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive` and I get the following error:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: edu/stanford/nlp/sempre/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by ppasupat** [comment]
Try removing `rlwrap` which seems to be causing the problem from that command.

**Comment by iScienceLuvr** [comment]
@ppasupat that gives this:

```
main() {
  Grammar.read {
    0 rules
  }
  Parser: 0 catUnaryRules (sorted), 0 nonCatUnaryRules (in trie)
  Dataset.read
  Learner.learn() {
    Iteration 0/0
  }
  Enter an utterance to parse or one of the following commands:
    (help): show this help message
    (status): prints out status of the system
    (get |option|): get a command-line option (e.g., (get Parser.verbose))
    (set |option| |value|): set a command-line option (e.g., (set Parser.verbose 5))
    (reload): reload the grammar/parameters
    (grammar): prints out the grammar
    (params [|file|]): dumps all the model parameters
    (select |candidate index|): show information about the |index|-th candidate of the last utterance.
    (accept |candidate index|): record the |index|-th candidate as the correct answer for the last utterance.
    (answer |answer|): record |answer| as the correct answer for the last utterance (e.g., (answer (list (number 3)))).
    (rule |lhs| (|rhs_1| ... |rhs_k|) |sem|): adds a rule to the grammar (e.g., (rule $Number ($TOKEN) (NumberFn)))
    (type |logical form|): perform type inference (e.g., (type (number 3)))
    (execute |logical form|): execute the logical form (e.g., (execute (call + (number 3) (number 4))))
    (def |key| |value|): define a macro to replace |key| with |value| in all commands (e.g., (def type fb:type.object type)))
    (context [(user |user|) (date |date|) (exchange |exchange|) (graph |graph|)]): prints out or set the context
  Press Ctrl-D to exit.
>  
```
That is what fixes it. So why does rlwrap affect it? Is is command going to be equivalent to `./run @mode=simple`?

**Comment by iScienceLuvr** [comment]
@ppasupat have you seen this?

**Comment by ppasupat** [comment]
The output is correct. There might be some problem with how `rlwrap` is set up on your machine. Unfortunately I'm not sure if I can help here, but you can always append `-n` to the run command, copy the output, and run it without `rlwrap`. Another way is to edit the `rlwrap` function in `run` so that it always returns `nil`.

Hopefully this will solve the issue.

**Comment by iScienceLuvr** [comment]
@ppasupat ok thanks!

**Comment by donglixp** [comment]
I also had the same error massage after using rlwrap. However, it is not a bug of rlwrap. This can be fixed by removing the ``alias java=***'' from your .bash_rc file.
