### ISSUE TITLE
Error "ant core"

### ISSUE THREAD

**Issue by raisondet** [percyliang/sempre#84]
Hello~ :)
I have some difficulties with installation.
When I run "ant core", there are a number of error messages. 

ubuntu@ip-172-31-27-159:~/sempre$ ant core
Buildfile: /home/ubuntu/sempre/build.xml

init:
     [exec] Wrote modules with 248 files to module-classes.txt: cache core corenlp freebase overnight tables
    [mkdir] Created dir: /home/ubuntu/sempre/classes
    [mkdir] Created dir: /home/ubuntu/sempre/libsempre

core:
     [echo] Compiling semparse: core
    [javac] Compiling 124 source files to /home/ubuntu/sempre/classes
    [javac] **/home/ubuntu/sempre/src/edu/stanford/nlp/sempre/AbstractReinforcementParserState.java:3: error: package com.google.common.collect does not exist**
    [javac] import com.google.common.collect.Sets;
    [javac]                                 ^
    [javac] **/home/ubuntu/sempre/src/edu/stanford/nlp/sempre/AbstractReinforcementParserState.java:4: error: package fig.basic does not exist**
    [javac] import fig.basic.LogInfo;
    [javac]                 ^
    [javac] **/home/ubuntu/sempre/src/edu/stanford/nlp/sempre/AbstractReinforcementParserState.java:5: error: package fig.basic does not exist**
    [javac] import fig.basic.MapUtils;

How can this be fixed?

**Comment by ppasupat** [comment]
Hello. Please try the following:
```
./pull-dependencies core
ant clean
ant core
```

**Comment by raisondet** [comment]
thanks. ppasupat!
I have already tried it. but same errors have occurred.

**Comment by ppasupat** [comment]
Could you check if the directory `lib` (`/home/ubuntu/sempre/lib` in your case) contains appropriate JAR files such as `guava-14.0.1.jar` and `fig.jar`?

**Comment by raisondet** [comment]
I find solution. I didn't install 'make' 'zip' ( i was using Amazon EC2 Server)
so, when i run "./pull-depencies core", it doesn't work fully.
After I install "make" (sudo apt-get install make) and "zip" (sudo apt-get install zip)
I success installation.

Thank you for your help :)

**Comment by raisondet** [comment]
ㅠㅠ
I have another difficulty.
When I run " ./run @mode=simple", there are a number of error messages.

ubuntu@ip-172-31-27-159:~/sempre$ ./run @mode=simple
**Error: Could not find or load main class edu.stanford.nlp.sempre.Main**
Command failed: java -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -Main.interactive

**Comment by ppasupat** [comment]
Try running `ant clean` and `ant` again. Maybe the classes are not fully compiled. In addition, please make sure that you use Java 8.

**Comment by raisondet** [comment]
Thanks : )

**Comment by ppasupat** [comment]
No problem. I will mark the issue as closed.
